/* JS */ gapi.loaded_0(function(_){var window=this;
_.m=function(a){throw a;};_.p=void 0;_.r=!0;_.s=null;_.u=!1;_.aa=function(){return function(a){return a}};_.x=function(){return function(){}};_.ba=function(a){return function(c){this[a]=c}};_.y=function(a){return function(){return this[a]}};_.ca=function(a){return function(){return a}};_.C=function(a,c,f){a=a.split(".");f=f||_.D;a[0]in f||!f.execScript||f.execScript("var "+a[0]);for(var g;a.length&&(g=a.shift());)a.length||c===_.p?f=f[g]?f[g]:f[g]={}:f[g]=c};
_.da=function(a){var c=typeof a;if("object"==c)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return c;var f=Object.prototype.toString.call(a);if("[object Window]"==f)return"object";if("[object Array]"==f||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==f||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==c&&"undefined"==typeof a.call)return"object";return c};_.kf=function(a){return a!==_.p};_.ea=function(a){return"array"==(0,_.da)(a)};_.re=function(a){var c=(0,_.da)(a);return"array"==c||"object"==c&&"number"==typeof a.length};_.fa=function(a){return"string"==typeof a};var ia=function(a,c,f){return a.call.apply(a.bind,arguments)};
var la=function(a,c,f){a||(0,_.m)(Error());if(2<arguments.length){var g=Array.prototype.slice.call(arguments,2);return function(){var f=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(f,g);return a.apply(c,f)}}return function(){return a.apply(c,arguments)}};_.H=function(a,c,f){_.H=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ia:la;return _.H.apply(_.s,arguments)};
_.ma=function(a,c){var f=Array.prototype.slice.call(arguments,1);return function(){var c=f.slice();c.push.apply(c,arguments);return a.apply(this,c)}};_.J=function(a,c){function f(){}f.prototype=c.prototype;a.T=c.prototype;a.prototype=new f;a.prototype.constructor=a};var _DumpException=function(a){(0,_.m)(a)};_.na=_.na||{};_.D=this;_.oa="closure_uid_"+(1E9*Math.random()>>>0);_.pa=Date.now||function(){return+new Date}; Function.prototype.bind=Function.prototype.bind||function(a,c){if(1<arguments.length){var f=Array.prototype.slice.call(arguments,1);f.unshift(this,a);return _.H.apply(_.s,f)}return(0,_.H)(this,a)};
_.Kh=window.gapi||{};_.ra=window.gadgets||{};_.L=window.osapi=window.osapi||{};_.google=window.google||{};
window.___jsl=window.___jsl||{};
(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"explicit"},appsapi:{plus_one_service:"/plus/v1"},client:{jsonpOverride:_.u},poshare:{hangoutContactPickerServer:"https://plus.google.com"},gappsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:_.u},appsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:_.u},
"oauth-flow":{authUrl:"https://accounts.google.com/o/oauth2/auth",proxyUrl:"https://accounts.google.com/o/oauth2/postmessageRelay",redirectUri:"postmessage"},iframes:{sharebox:{params:{json:"&"},url:":socialhost:/:session_prefix:_/sharebox/dialog"},plus:{url:":socialhost:/u/:session_index:/_/pages/badge"},":socialhost:":"https://apis.google.com",card:{params:{s:"#",userid:"&"},url:":socialhost:/:session_prefix:_/hovercard/internalcard"},":signuphost:":"https://plus.google.com",plusone:{url:":socialhost:/:session_prefix:_/+1/fastbutton?usegapi=1"},
plus_share:{url:":socialhost:/:session_prefix:_/+1/sharebutton?plusShare=true"},plus_circle:{url:":socialhost:/:session_prefix:_/widget/plus/circle"},configurator:{url:":socialhost:/:session_prefix:_/plusbuttonconfigurator"},appcirclepicker:{url:":socialhost:/:session_prefix:_/widget/render/appcirclepicker"},":source:":"1p"},poclient:{update_session:"google.updateSessionCallback"},"googleapis.config":{methods:{"pos.plusones.list":_.r,"pos.plusones.get":_.r,"pos.plusones.insert":_.r,"pos.plusones.delete":_.r,
"pos.plusones.getSignupState":_.r},requestCache:{enabled:_.r},versions:{pos:"v1"},rpc:"/rpc",root:"https://content.googleapis.com","root-1p":"https://clients6.google.com",sessionCache:{enabled:_.r},transport:{isProxyShared:_.r},xd3:"/static/proxy.html",developerKey:"AIzaSyCKSbrvQasunBoV16zDH9R33D88CeLr9gQ",auth:{useInterimAuth:_.u}},report:{apis:["iframes\\..*","gadgets\\..*","gapi\\.appcirclepicker\\..*","gapi\\.client\\..*"],rate:1E-4}});

window.___jsl=window.___jsl||{};(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"onload"},iframes:{":source:":"3p"}});
_.N=function(a,c,f){return a[c]=a[c]||f};_.Za=function(a){return"function"===typeof a};_.gb=function(a){return String(a).replace(hb,"&amp;").replace(ib,"&lt;").replace(jb,"&gt;").replace(kb,"&quot;").replace(lb,"&#39;")};_.O=function(){var a;if((a=Object.create)&&_.ta.test(a))a=a(_.s);else{a={};for(var c in a)a[c]=_.p}return a};_.Qa=function(a,c){return Object.prototype.hasOwnProperty.call(a,c)};_.Ra=function(a,c){a=a||{};for(var f in a)(0,_.Qa)(a,f)&&(c[f]=a[f])};
_.fb=function(a,c){a||(0,_.m)(Error(c||""))};_.Ua=function(a,c,f){var g=RegExp("([#].*&|[#])"+c+"=([^&#]*)","g");c=RegExp("([?#].*&|[?#])"+c+"=([^&#]*)","g");if(a=a&&(g.exec(a)||c.exec(a)))try{f=(0,window.decodeURIComponent)(a[2])}catch(h){}return f};_.bb=function(a){a=a.match(cb);var c=(0,_.O)();c.yc=a[1];c.mb=a[3]?[a[3]]:[];c.Vf=a[5]?[a[5]]:[];return c};_.Hb=function(a){a=a?a.split("&"):[];for(var c=[],f=0;f<a.length;f++){var g=a[f].split("=",2);c.push([(0,window.decodeURIComponent)(g[0]),(0,window.decodeURIComponent)(g[1])])}return c};
_.ab=function(a){return a.yc+(0<a.mb.length?"?"+a.mb.join("&"):"")+(0<a.Vf.length?"#"+a.Vf.join("&"):"")};var $a=function(a,c){var f=[];if(a)for(var g in a)if((0,_.Qa)(a,g)&&a[g]!=_.s){var h=c?c(a[g]):a[g];f.push((0,window.encodeURIComponent)(g)+"="+(0,window.encodeURIComponent)(h))}return f};_.db=function(a,c,f,g){a=(0,_.bb)(a);a.mb.push.apply(a.mb,$a(c,g));a.Vf.push.apply(a.Vf,$a(f,g));return(0,_.ab)(a)};
_.ua=function(a,c){var f="";2E3<c.length&&(f=c.substring(2E3),c=c.substring(0,2E3));var g=a.createElement("div"),h=a.createElement("a");h.href=c;g.appendChild(h);g.innerHTML=g.innerHTML;c=String(g.firstChild.href);g.parentNode&&g.parentNode.removeChild(g);return c+f};_.Yb=function(a){return aB.test(a)};_.Va=function(a,c,f){Sa(a,c,f,"add","at")};_.wc=function(a,c,f){Sa(a,c,f,"remove","de")};
var Sa=function(a,c,f,g,h){if(a[g+"EventListener"])a[g+"EventListener"](c,f,_.u);else if(a[h+"tachEvent"])a[h+"tachEvent"]("on"+c,f)};_.eb=function(a){for(;a.firstChild;)a.removeChild(a.firstChild)};_.Sc=function(a){return _.wa.dpo?_.wa.h:(0,_.Ua)(a,"jsh",_.wa.h)};_.le=function(a){return(0,_.Ua)(a,"_bsh",_.wa.bsh)};_.Qe=function(){return _.wa.onl};_.Xf=function(a){_.wa.onl=a};_.Rh=function(){return!!_.wa.oa};var ya=function(a){var c=window.___jsl=window.___jsl||{};c[a]=c[a]||[];return c[a]};
var za=function(a){var c=window.___jsl=window.___jsl||{};c.cfg=!a&&c.cfg||{};return c.cfg};var Aa=function(a){return"object"===typeof a&&/\[native code\]/.test(a.push)};var Ba=function(a,c){if(c)for(var f in c)c.hasOwnProperty(f)&&(a[f]&&c[f]&&"object"===typeof a[f]&&"object"===typeof c[f]&&!Aa(a[f])&&!Aa(c[f])?Ba(a[f],c[f]):c[f]&&"object"===typeof c[f]?(a[f]=Aa(c[f])?[]:{},Ba(a[f],c[f])):a[f]=c[f])};
var Da=function(a){if(a&&!/^\s+$/.test(a)){for(;0==a.charCodeAt(a.length-1);)a=a.substring(0,a.length-1);var c;try{c=window.JSON.parse(a)}catch(f){}if("object"===typeof c)return c;try{c=(new Function("return ("+a+"\n)"))()}catch(g){}if("object"===typeof c)return c;try{c=(new Function("return ({"+a+"\n})"))()}catch(h){}return"object"===typeof c?c:{}}};
var Ea=function(a){za(_.r);var c=window.___gcfg,f=ya("cu");if(c&&c!==window.___gu){var g={};Ba(g,c);f.push(g);window.___gu=c}var c=ya("cu"),h=window.document.scripts||window.document.getElementsByTagName("script")||[],g=[],l=[];l.push.apply(l,ya("us"));for(var n=0;n<h.length;++n)for(var q=h[n],t=0;t<l.length;++t)q.src&&0==q.src.indexOf(l[t])&&g.push(q);0==g.length&&0<h.length&&h[h.length-1].src&&g.push(h[h.length-1]);for(h=0;h<g.length;++h)g[h].getAttribute("gapi_processed")||(g[h].setAttribute("gapi_processed",
_.r),(l=g[h])?(n=l.nodeType,l=3==n||4==n?l.nodeValue:l.textContent||l.innerText||l.innerHTML||""):l=_.p,(l=Da(l))&&c.push(l));a&&(g={},Ba(g,a),f.push(g));g=ya("cd");a=0;for(c=g.length;a<c;++a)Ba(za(),g[a]);g=ya("ci");a=0;for(c=g.length;a<c;++a)Ba(za(),g[a]);a=0;for(c=f.length;a<c;++a)Ba(za(),f[a])};_.P=function(a,c){if(!a)return za();for(var f=a.split("/"),g=za(),h=0,l=f.length;g&&"object"===typeof g&&h<l;++h)g=g[f[h]];return h===f.length&&g!==_.p?g:c};
_.Fa=function(a,c){var f=a;if("string"===typeof a){for(var g=f={},h=a.split("/"),l=0,n=h.length;l<n-1;++l)var q={},g=g[h[l]]=q;g[h[l]]=c}Ea(f)};var Ga=function(){var a=window.__GOOGLEAPIS;a&&(a.googleapis&&!a["googleapis.config"]&&(a["googleapis.config"]=a.googleapis),(0,_.N)(_.wa,"ci",[]).push(a),window.__GOOGLEAPIS=_.p)};_.Q=function(a,c){c="function"==typeof _.Ha&&(0,_.Ha)(a,c)||c;(0,_.C)(a,c,_.p)};
var lb;var kb;var jb;var ib;var hb;_.Ia=window;_.Ja=window.document;_.sb=_.Ia.location;_.ta=/\[native code\]/;hb=/&/g;ib=/</g;jb=/>/g;kb=/"/g;lb=/'/g;_.Yi=(0,_.N)(_.Ia,"gapi",{});var cb=/^([^?#]*)(\?([^#]*))?(\#(.*))?$/,aB=/^https?:\/\/[^\/%\\?#\s]+\/[^\s]*$/i;_.wa=(0,_.N)(_.Ia,"___jsl",(0,_.O)());(0,_.N)(_.wa,"I",0);(0,_.N)(_.wa,"hel",10);Ga&&Ga();Ea();(0,_.Q)("gapi.config.get",_.P);(0,_.Q)("gapi.config.update",_.Fa);
_.jd=function(a){return!!a&&"object"===typeof a&&_.ta.test(a.push)};_.fj=function(a,c,f){if(a){(0,_.fb)((0,_.jd)(a),"arrayForEach was called with a non array value");for(var g=0;g<a.length;g++)c.call(f,a[g],g)}};_.DC=function(a,c,f){if(a)if((0,_.jd)(a))(0,_.fj)(a,c,f);else{(0,_.fb)("object"===typeof a,"objectForEach was called with a non object value");f=f||a;for(var g in a)(0,_.Qa)(a,g)&&a[g]!==_.p&&c.call(f,a[g],g)}};
var Bj=function(a){a=a.sort();for(var c=[],f=_.p,g=0;g<a.length;g++){var h=a[g];h!=f&&c.push(h);f=h}return c};var bk=function(){var a=[],c=_.wa.H;c&&(0,_.DC)(c,function(c){a.push.apply(a,c.L)});return Bj(a)};_.wd=function(a){if(_.ta.test(Object.keys))return Object.keys(a);var c=[],f;for(f in a)(0,_.Qa)(a,f)&&c.push(f);return c};
var La=function(a){if(vk===_.p){var c=(0,_.P)("report")||{},f=c.rate,g=Math.random();if(vk="number"===typeof f&&f>g)wk["rate."+f+"-"+g]=_.r,Wl=c.timeout||1E3,Tm=c.host||"https://plus.google.com",Um=c.path||"/_/widget/report",vn=c.apis||[]}if(!vk)return _.u;if(vn)for(c=0;c<vn.length;c++)if(RegExp("^"+vn[c]+"$").test(a))return _.r;return _.u};var Ma=function(a){delete Na[a]};
var wn=function(){xn&&(_.Ia.clearTimeout(xn),xn=0);xn=_.Ia.setTimeout(function(){var a;a=window.document.location.href;var c=(0,_.wd)(wk).join(":");a=[Tm,Um,"?api=",(0,window.encodeURIComponent)(c),"&url=",(0,window.encodeURIComponent)(a),"&loaded=",(0,window.encodeURIComponent)(bk().join(":"))].join("");wk=(0,_.O)();var c=new window.Image,f=Pa++;Na[f]=c;c.onload=c.onerror=(0,_.ma)(Ma,f);c.src=a;xn=0},Wl)}; _.Ha=function(a,c){var f=c;(0,_.Za)(c)&&La(a)&&(f=function(f){An[a]||(wk[a]=_.r,An[a]=_.r,wn());return c.apply(this,arguments)});return f};var vk,Tm,Um,Wl,xn,vn,Na={},Pa=0,An=(0,_.O)(),wk=(0,_.O)();


_.Rb=window.gapi&&window.gapi.util||{};
_.Rb.Pq=function(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);/^[\w\-]*:\/\//.test(a)||(a=window.location.href);var c=a.substring(a.indexOf("://")+3),f=c.indexOf("/");-1!=f&&(c=c.substring(0,f));a=a.substring(0,a.indexOf("://"));"http"!==a&&"https"!==a&&"chrome-extension"!==a&&"file"!==a&&(0,_.m)(Error("Pa"));var f="",g=c.indexOf(":");if(-1!=g){var h=c.substring(g+1),c=c.substring(0,g);if("http"===a&&"80"!==h||"https"===a&& "443"!==h)f=":"+h}return a+"://"+c+f};

_.kd=function(a){Kd&&Kd.log&&Kd.log(a)};_.ke=function(){};var Kd=window.console;
if(window.JSON&&window.JSON.parse&&window.JSON.stringify)_.Kb={parse:function(a){try{return window.JSON.parse(a)}catch(c){return _.u}},stringify:window.JSON.stringify};window.JSON&&window.JSON.parse&&window.JSON.stringify||(_.Kb=function(){function a(f){var g,h,l;g=/[\"\\\x00-\x1f\x7f-\x9f]/g;switch(typeof f){case "string":return g.test(f)?'"'+f.replace(g,function(a){var f=c[a];if(f)return f;f=a.charCodeAt();return"\\u00"+Math.floor(f/16).toString(16)+(f%16).toString(16)})+'"':'"'+f+'"';case "number":return(0,window.isFinite)(f)?String(f):"null";case "boolean":case "null":return String(f);case "object":if(!f)return"null";g=[];if("number"===typeof f.length&&!f.propertyIsEnumerable("length")){l=
f.length;for(h=0;h<l;h+=1)g.push(a(f[h])||"null");return"["+g.join(",")+"]"}for(h in f)!/___$/.test(h)&&f.hasOwnProperty(h)&&"string"===typeof h&&(l=a(f[h]))&&g.push(a(h)+":"+l);return"{"+g.join(",")+"}"}return""}var c={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return{stringify:a,parse:function(a){return/^[\],:{}\s]*$/.test(a.replace(/\\["\\\/b-u]/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g, ""))?eval("("+a+")"):_.u}}}());
_.Kb.Ck=function(a){var c={};if(a===_.s||a===_.p)return c;for(var f in a)if(a.hasOwnProperty(f)){var g=a[f];_.s!==g&&_.p!==g&&(c[f]="string"===typeof g?g:_.Kb.stringify(g))}return c};(0,_.Q)("gadgets.json.flatten",_.Kb.Ck);(0,_.Q)("gadgets.json.parse",_.Kb.parse);(0,_.Q)("gadgets.json.stringify",_.Kb.stringify);(0,_.Q)("gadgets.json.flatten",_.Kb.Ck);(0,_.Q)("gadgets.json.parse",_.Kb.parse);(0,_.Q)("gadgets.json.stringify",_.Kb.stringify);

_.R=_.R||{};
_.Nb=function(a){for(var c=0;c<this.length;c++)if(this[c]===a)return c;return-1};_.R=_.R||{};
(function(){var a=_.s;_.R.$e=function(c){var f="undefined"===typeof c;if(a!==_.s&&f)return a;var g={};c=c||window.location.href;var h=c.indexOf("?"),l=c.indexOf("#");c=(-1===l?c.substr(h+1):[c.substr(h+1,l-h-1),"&",c.substr(l+1)].join("")).split("&");for(var h=window.decodeURIComponent?window.decodeURIComponent:window.unescape,l=0,n=c.length;l<n;++l){var q=c[l].indexOf("=");if(-1!==q){var t=c[l].substring(0,q),q=c[l].substring(q+1),q=q.replace(/\+/g," ");try{g[t]=h(q)}catch(v){}}}f&&(a=g);return g}; _.R.$e()})();
(0,_.Q)("gadgets.util.getUrlParameters",_.R.$e);
var jz=function(a){this.G=a;this.B=_.Ia;this.qa=this.Ka;if(this.G.CF){this.B=this.G.kq(this.B,this.G.CF);a=this.B.document;var c=a.createElement("script");c.setAttribute("type","text/javascript");c.text="window.doPostMsg=function(w,s,o) {window.setTimeout(function(){w.postMessage(s,o);},0);};";a.body.appendChild(c);this.qa=this.B.doPostMsg}this.ha={};this.M={};a=(0,_.H)(this.wc,this);(0,_.Va)(this.B,"message",a);(0,_.N)(_.wa,"RPMQ",[]).push(a);this.B!=this.B.parent&&CC(this,this.B.parent,"{h:'"+(0,window.escape)(this.B.name)+
"'}","*")};var lz=function(a,c){var f=_.s;0===c.indexOf("{h:'")&&c.indexOf("'}")===c.length-2&&(f=(0,window.unescape)(c.substring(4,c.length-2)));return f};var kz=function(a,c){var f=_.Kb.parse(c);return f!==_.s&&"object"===typeof f&&!!f.g};var CC=function(a,c,f,g){var h=kz(a,f)?"":"!_";(0,_.ke)("gapi.rpc.send("+Qz+"): "+(!f||512>=f.length?f:f.substr(0,512)+"... ("+f.length+" bytes)"));a.qa(c,h+f,g)};var mz=function(){};
var nz=function(a,c){"/"==c.charAt(0)&&(c=c.substring(1),a=_.Ia.top);for(var f=c.split("/");f.length;){var g;g=f.shift();"{"==g.charAt(0)&&"}"==g.charAt(g.length-1)&&(g=g.substring(1,g.length-1));if(".."===g)a=a==a.parent?a.opener:a.parent;else if(".."!==g&&a.frames[g])a=a.frames[g],"postMessage"in a||(0,_.m)("Not a window");else return _.s}return a};var oz=function(a){return(a=pz[a])&&a.ve};
var qz=function(a){if(a.f in{})return _.u;var c=a.t,f=pz[a.r];a=a.origin;return f&&(f.ve===c||!f.ve&&!c)&&(a===f.origin||"*"===f.origin)};var rz=function(a){var c=a.id.split("/"),f=c[c.length-1],g=a.origin;return function(a){var c=a.origin;return a.f==f&&(g==c||"*"==g)}};_.sz=function(a,c,f){a=tz(a);uz[a.name]={Ip:c,lf:a.lf,Us:f||qz};vz()};_.wz=function(a){delete uz[tz(a).name]};var xz=function(a,c){var f=yz["_"+a];f&&f[1](this)&&f[0].call(this,c)};
var zz=function(a){var c=a.c;if(!c)return mz;var f=a.r,g=a.g?"legacy__":"";return function(){var a=[].slice.call(arguments,0);a.unshift(f,g+"__cb",_.s,c);_.Az.apply(_.s,a)}};var Bz=function(a){Cz=a};var Dz=function(a){Ez[a]||(Ez[a]=_.Ia.setTimeout(function(){Ez[a]=_.u;Fz(a)},0))};var Fz=function(a){var c=pz[a];if(c&&c.Tb){var f=c.kj;for(c.kj=[];f.length;)Gz.send(a,_.Kb.stringify(f.shift()),c.origin)}};var tz=function(a){return 0===a.indexOf("legacy__")?{name:a.substring(8),lf:_.r}:{name:a,lf:_.u}};
var vz=function(){for(var a=(0,_.P)("rpc/residenceSec")||60,c=(new Date).getTime()/1E3,f=0,g;g=Hz[f];++f){var h=g.qf;if(!h||0<a&&c-g.timestamp>a)Hz.splice(f,1),--f;else{var l=h.s,n=uz[l]||uz["*"];if(n)if(Hz.splice(f,1),--f,h.origin=g.origin,g=zz(h),h.callback=g,n.Us(h)){if("__cb"!==l&&!!n.lf!=!!h.g)break;h=n.Ip.apply(h,h.a);h!==_.p&&g(h)}else(0,_.ke)("gapi.rpc.rejected("+Qz+"): "+l)}}};var Iz=function(a,c,f){Hz.push({qf:a,origin:c,timestamp:(new Date).getTime()/1E3});f||vz()};
var Jz=function(a,c){var f=_.Kb.parse(a);Iz(f,c,_.u)};var Kz=function(a){for(;a.length;)Iz(a.shift(),this.origin,_.r);vz()};var Lz=function(a){var c=_.u;a=a.split("|");var f=a[0];0<=f.indexOf("/")&&(c=_.r);return{id:f,origin:a[1]||"*",Ki:c}};
_.Mz=function(a,c,f,g){var h=Lz(a);g&&(_.Ia.frames[h.id]=_.Ia.frames[h.id]||g);a=h.id;if(!pz.hasOwnProperty(a)){f=f||_.s;g=h.origin;if(".."===a)g=_.Rb.Pq(Oz),f=f||Pz;else if(!h.Ki){var l=_.Ja.getElementById(a);l&&(l=l.src,g=_.Rb.Pq(l),f=f||Nz(l).rpctoken)}"*"===h.origin&&g||(g=h.origin);pz[a]={ve:f,kj:[],origin:g,hs:c,xm:function(){var c=a;pz[c].Tb=1;Fz(c)}};Gz.sf(a,pz[a].xm)}return pz[a].xm};
_.Az=function(a,c,f,g){a=a||"..";(0,_.Mz)(a);a=a.split("|",1)[0];var h=[].slice.call(arguments,3),l=c,n=f,q=Qz,t=Pz,v=pz[a],w=q,A=Lz(a);if(v&&".."!==a){if(A.Ki){if(!(w=pz[a].hs)){for(var w=_.s,w=Cz?Cz.substring(1).split("/"):[Qz],t=w.length-1,F=_.Ia.parent;F!==_.Ia.top;){var z=F.parent;if(!t--){for(var I=_.s,E=z.frames.length,K=0;K<E;++K)z.frames[K]==F&&(I=K);w.unshift("{"+I+"}")}F=z}w="/"+w.join("/")}}else w=q="..";t=v.ve}v=l;n&&A?(F=qz,A.Ki&&(F=rz(A)),yz["_"+ ++Rz]=[n,F],A=Rz):A=_.s;h={s:v,f:q,
r:w,t:t,c:A,a:h};l=tz(l);h.s=l.name;h.g=l.lf;pz[a].kj.push(h);Dz(a)};jz.prototype.wc=function(a){var c=String(a.data);(0,_.ke)("gapi.rpc.receive("+Qz+"): "+(!c||512>=c.length?c:c.substr(0,512)+"... ("+c.length+" bytes)"));var f=0!==c.indexOf("!_");f||(c=c.substring(2));var g=kz(this,c);if(!f&&!g){if(!g&&(f=lz(this,c))){if(this.ha[f])this.ha[f]();else this.M[f]=1;return}var h=a.origin,l=this.G.zp;_.Ia.setTimeout(function(){l(c,h)},0)}}; jz.prototype.sf=function(a,c){".."===a||this.M[a]?(c(),delete this.M[a]):this.ha[a]=c};jz.prototype.Ka=function(a,c,f){a.postMessage(c,f)};jz.prototype.send=function(a,c,f){(a=this.G.kq(this.B,a))&&CC(this,a,c,f)};
var Rz=0,Hz=[],pz={},uz={},Nz=_.R.$e,Sz=Nz(),Pz=Sz.rpctoken,Oz=Sz.parent||_.Ja.referrer,Wp=Sz.rly,Qz=Wp||(_.Ia!==_.Ia.top||_.Ia.opener)&&_.Ia.name||"..",Cz=_.s,Ez={},Gz={send:mz,sf:mz},yz={};if("function"===typeof _.Ia.postMessage||"object"===typeof _.Ia.postMessage)Gz=new jz({CF:Wp?"../"+Wp:_.s,zp:Jz,kq:nz,ZN:Qz,$f:oz,qO:Bz}),(0,_.sz)("__cb",xz,(0,_.ca)(_.r)),(0,_.sz)("_processBatch",Kz,(0,_.ca)(_.r)),(0,_.Mz)("..");

_.Ob=_.Ob||{};_.Ob.Xk=function(){var a=0,c=0;window.self.innerHeight?(a=window.self.innerWidth,c=window.self.innerHeight):window.document.documentElement&&window.document.documentElement.clientHeight?(a=window.document.documentElement.clientWidth,c=window.document.documentElement.clientHeight):window.document.body&&(a=window.document.body.clientWidth,c=window.document.body.clientHeight);return{width:a,height:c}};

_.Ob=_.Ob||{};
(function(){function a(a,f){window.getComputedStyle(a,"").getPropertyValue(f).match(/^([0-9]+)/);return(0,window.parseInt)(RegExp.$1,10)}_.Ob.Jh=function(){var c=_.Ob.Xk().height,f=window.document.body,g=window.document.documentElement;if("CSS1Compat"===window.document.compatMode&&g.scrollHeight)return g.scrollHeight!==c?g.scrollHeight:g.offsetHeight;if(0<=window.navigator.userAgent.indexOf("AppleWebKit")){c=0;for(f=[window.document.body];0<f.length;){var h=f.shift(),g=h.childNodes;if("undefined"!==
typeof h.style){var l=h.style.overflowY;l||(l=(l=window.document.defaultView.getComputedStyle(h,_.s))?l.overflowY:_.s);if("visible"!=l&&"inherit"!=l&&(l=h.style.height,l||(l=(l=window.document.defaultView.getComputedStyle(h,_.s))?l.height:""),0<l.length&&"auto"!=l))continue}for(h=0;h<g.length;h++){l=g[h];if("undefined"!==typeof l.offsetTop&&"undefined"!==typeof l.offsetHeight)var n=l.offsetTop+l.offsetHeight+a(l,"margin-bottom"),c=Math.max(c,n);f.push(l)}}return c+a(window.document.body,"border-bottom")+ a(window.document.body,"margin-bottom")+a(window.document.body,"padding-bottom")}if(f&&g)return h=g.scrollHeight,l=g.offsetHeight,g.clientHeight!==l&&(h=f.scrollHeight,l=f.offsetHeight),h>c?h>l?h:l:h<l?h:l}})();

_.Bn=function(a){var c=(0,_.P)("googleapis.config/sessionIndex");c==_.s&&(c=window.__X_GOOG_AUTHUSER);if(c==_.s){var f=window.google;f&&(c=f.authuser)}c==_.s&&(a=a||window.location.href,c=(0,_.Ua)(a,"authuser")||_.s,c==_.s&&(c=(c=a.match(Cn))?c[1]:_.s));return c==_.s?_.s:String(c)};_.Dn=function(a){var c=(0,_.P)("googleapis.config/sessionDelegate");c==_.s&&(c=(a=(a||window.location.href).match(Un))?a[1]:_.s);return c==_.s?_.s:String(c)}; _.co=function(a,c){var f=(0,_.Bn)(a)||c,g=(0,_.Dn)(a),h="";f&&(h+="u/"+f+"/");g&&(h+="b/"+g+"/");return h||_.s};
var Cn=/^https?:\/\/(?:\w|[\-\.])+\.google\.(?:\w|[\-:\.])+(?:\/[^\?\#]*)?\/u\/(\d)\//,Un=/^https?:\/\/(?:\w|[\-\.])+\.google\.(?:\w|[\-:\.])+(?:\/[^\?\#]*)?\/b\/(\d{10,})\//;
var wb=function(){};var xb=function(){this.B=[];this.M=[];this.Ka=[];this.ha=[];this.ha[0]=128;for(var a=1;64>a;++a)this.ha[a]=0;this.reset()};
var yb=function(a,c,f){f||(f=0);var g=a.Ka;if((0,_.fa)(c))for(var h=0;16>h;h++)g[h]=c.charCodeAt(f)<<24|c.charCodeAt(f+1)<<16|c.charCodeAt(f+2)<<8|c.charCodeAt(f+3),f+=4;else for(h=0;16>h;h++)g[h]=c[f]<<24|c[f+1]<<16|c[f+2]<<8|c[f+3],f+=4;for(h=16;80>h;h++){var l=g[h-3]^g[h-8]^g[h-14]^g[h-16];g[h]=(l<<1|l>>>31)&4294967295}c=a.B[0];f=a.B[1];for(var n=a.B[2],q=a.B[3],t=a.B[4],v,h=0;80>h;h++)40>h?20>h?(l=q^f&(n^q),v=1518500249):(l=f^n^q,v=1859775393):60>h?(l=f&n|q&(f|n),v=2400959708):(l=f^n^q,v=3395469782), l=(c<<5|c>>>27)+l+t+v+g[h]&4294967295,t=q,q=n,n=(f<<30|f>>>2)&4294967295,f=c,c=l;a.B[0]=a.B[0]+c&4294967295;a.B[1]=a.B[1]+f&4294967295;a.B[2]=a.B[2]+n&4294967295;a.B[3]=a.B[3]+q&4294967295;a.B[4]=a.B[4]+t&4294967295};_.ep=function(){this.B=new xb};
(0,_.J)(xb,wb);xb.prototype.reset=function(){this.B[0]=1732584193;this.B[1]=4023233417;this.B[2]=2562383102;this.B[3]=271733878;this.B[4]=3285377520;this.qa=this.G=0};xb.prototype.update=function(a,c){(0,_.kf)(c)||(c=a.length);for(var f=c-64,g=0,h=this.M,l=this.G;g<c;){if(0==l)for(;g<=f;)yb(this,a,g),g+=64;if((0,_.fa)(a))for(;g<c;){if(h[l]=a.charCodeAt(g),++l,++g,64==l){yb(this,h);l=0;break}}else for(;g<c;)if(h[l]=a[g],++l,++g,64==l){yb(this,h);l=0;break}}this.G=l;this.qa+=c};
xb.prototype.xk=function(){var a=[],c=8*this.qa;56>this.G?this.update(this.ha,56-this.G):this.update(this.ha,64-(this.G-56));for(var f=63;56<=f;f--)this.M[f]=c&255,c/=256;yb(this,this.M);for(f=c=0;5>f;f++)for(var g=24;0<=g;g-=8)a[c]=this.B[f]>>g&255,++c;return a};
_.k=_.ep.prototype;_.k.reset=function(){this.B.reset()};_.k.fG=function(a){this.B.update(a)};_.k.hE=function(){return this.B.xk()};_.k.$C=function(a){a=(0,window.unescape)((0,window.encodeURIComponent)(a));for(var c=[],f=0,g=a.length;f<g;++f)c.push(a.charCodeAt(f));this.fG(c)};_.k.Of=function(){for(var a=this.hE(),c="",f=0;f<a.length;f++)c+="0123456789ABCDEF".charAt(Math.floor(a[f]/16))+"0123456789ABCDEF".charAt(a[f]%16);return c};

var mb=function(){var a=(0,_.Qe)();if(!a){a=(0,_.O)();(0,_.Xf)(a);var c=(0,_.O)();a.e=function(a){var g=c[a];g&&(delete c[a],g())};a.a=function(a,g){c[a]=g};a.r=function(a){delete c[a]}}return a};var nb=function(a,c){var f=c.onload;return(0,_.Za)(f)?(mb().a(a,f),f):_.s};var ob=function(a){(0,_.fb)(/^\w+$/.test(a),"Unsupported id - "+a);mb();return'onload="window.___jsl.onl.e(&#34;'+a+'&#34;)"'};var pb=function(a){mb().r(a)};
_.uq=function(a,c){var f,g=0;do f=c.id||["I",ub++,"_",(new Date).getTime()].join("");while(a.getElementById(f)&&5>++g);(0,_.fb)(5>g,"Error creating iframe id");return f};
_.qa=function(a,c,f,g){var h={},l={};(0,_.Ra)(g.queryParams||{},h);(0,_.Ra)(g.fragmentParams||{},l);var n=g.pfname,q=(0,_.O)();q.id=f;q.parent=a.location.protocol+"//"+a.location.host;f=(0,_.Ua)(a.location.href,"parent");n=n||"";!n&&f&&(n=(0,_.Ua)(a.location.href,"id",""),f=(0,_.Ua)(a.location.href,"pfname",""),n=n?f+"/"+n:"");q.pfname=n;(0,_.Ra)(q,l);(q=(0,_.Ua)(c,"rpctoken")||h.rpctoken||l.rpctoken)||(q=l.rpctoken=g.rpctoken||String(Math.round(1E8*(0,_.wq)())));g.rpctoken=q;q=a.location.href;a=
(0,_.O)();(n=(0,_.le)(q))&&(a._bsh=n);(q=(0,_.Sc)(q))&&(a.jsh=q);g.hintInFragment?(0,_.Ra)(a,l):(0,_.Ra)(a,h);return(0,_.db)(c,h,l,g.paramsSerializer)};var hc=function(a){(0,_.fb)(!a||(0,_.Yb)(a),"Illegal url for new iframe - "+a)};
_.yq=function(a,c,f,g,h){hc(f.src);var l,n=nb(g,f),q=n?ob(g):"";try{l=a.createElement('<iframe frameborder="'+(0,_.gb)(String(f.frameborder))+'" scrolling="'+(0,_.gb)(String(f.scrolling))+'" '+q+' name="'+(0,_.gb)(String(f.name))+'"/>')}catch(t){l=a.createElement("iframe"),n&&(l.onload=function(){l.onload=_.s;n.call(this)},pb(g))}for(var v in f)a=f[v],"style"===v&&"object"===typeof a?(0,_.Ra)(a,l.style):rb[v]||l.setAttribute(v,String(a));(v=h&&h.beforeNode||_.s)||h&&h.dontclear||(0,_.eb)(c);c.insertBefore(l,
v);l=v?v.previousSibling:c.lastChild;f.allowtransparency&&(l.allowTransparency=_.r);return l};var jc=function(a,c){if(!kc||(0,_.P)("oauth-flow/authAware")){var f=(0,_.Bn)()||"0",g=(0,_.Dn)(),h=(0,_.co)(_.p,f),l=(0,_.P)("oauth-flow/authAware")?"isLoggedIn":"googleapis.config/signedIn";(l=(0,_.P)(l)===_.u?"_/im/":"")&&(h="");kc={socialhost:(0,_.P)("iframes/:socialhost:"),session_index:f,session_delegate:g,session_prefix:h,im_prefix:l}}return kc[c]||""};
_.mc=function(a){return(0,_.ua)(_.Ja,a.replace(nc,jc))};
_.tb=function(a,c,f){var g=f||{};f=g.attributes||{};(0,_.fb)(!g.allowPost||!f.onload,"onload is not supported by post iframe");var h=f=a;_.zd.test(f)&&(h=(0,_.P)("iframes/"+h.substring(1)+"/url"),(0,_.fb)(!!h,"Unknown iframe url config for - "+f));a=(0,_.mc)(h);f=c.ownerDocument||_.Ja;h=(0,_.uq)(f,g);a=(0,_.qa)(f,a,h,g);var l=(0,_.O)();(0,_.Ra)(_.vb,l);(0,_.Ra)(g.attributes,l);l.name=l.id=h;l.src=a;g.eurl=a;if((g||{}).allowPost&&2E3<a.length){var n=(0,_.bb)(a);l.src="";l["data-postorigin"]=a;a=(0,_.yq)(f,
c,l,h);var q;if(-1!=window.navigator.userAgent.indexOf("WebKit")){q=a.contentWindow.document;q.open();var l=q.createElement("div"),t={},v=h+"_inner";t.name=v;t.src="";t.style="display:none";(0,_.yq)(f,l,t,v,g)}g=(0,_.Hb)(n.mb[0]);n.mb=[];l=(0,_.ab)(n);n=f.createElement("form");n.action=l;n.method="POST";n.target=h;n.style.display="none";for(h=0;h<g.length;h++)l=f.createElement("input"),l.type="hidden",l.name=g[h][0],l.value=g[h][1],n.appendChild(l);c.appendChild(n);n.submit();n.parentNode.removeChild(n); q&&q.close();c=a}else c=(0,_.yq)(f,c,l,h,g);return c};var kc;
var ub;var rb;_.vb={allowtransparency:"true",frameborder:"0",hspace:"0",marginheight:"0",marginwidth:"0",scrolling:"no",style:"",tabindex:"0",vspace:"0",width:"100%"};rb={allowtransparency:_.r,onload:_.r};ub=0;var nc;_.zd=/^:[\w]+$/;nc=/:([a-zA-Z_]+):/g;
_.wq=function(){var a;Jb?(a=new _.Ia.Uint32Array(1),Ib.getRandomValues(a),a=Number("0."+a[0])):(a=Ab,a+=(0,window.parseInt)(Gb.substr(0,20),16),Gb=Eb(Gb),a=a/(Bb+Math.pow(16,20)));return a};var zb=function(a){a=a||_.Ia.event;var c=a.screenX+a.clientX<<16,c=c+(a.screenY+a.clientY),c=(new Date).getTime()%1E6*c;Ab=Ab*c%Bb;0<Cb&&++Db==Cb&&(0,_.wc)(_.Ia,"mousemove",zb)};var Eb=function(a){var c=new _.ep;c.$C(a);return c.Of()};var Ib=_.Ia.crypto,Jb=_.u,Cb=0,Db=0,Ab=1,Bb=0,Gb="",Jb=!!Ib&&"function"==typeof Ib.getRandomValues; Jb||(Bb=1E6*(window.screen.width*window.screen.width+window.screen.height),Gb=Eb(_.Ja.cookie+"|"+_.Ja.location+"|"+(new Date).getTime()+"|"+Math.random()),Cb=(0,_.P)("random/maxObserveMousemove")||0,0!=Cb&&(0,_.Va)(_.Ia,"mousemove",zb));


_.Tz=function(){this.Rd=this.Kf=_.s;this.Gh=_.u};_.Tz.prototype.lc=function(a){if(this.Kf){var c=this.Kf;a instanceof _.Tz?a.Ed(c):c(a);this.Kf=_.s}else this.Rd=a,this.Gh=_.r};_.Tz.prototype.Ed=function(a){this.Kf=a;if(this.Gh){var c=this.Rd;c instanceof _.Tz?c.Ed(a):a(c);this.Gh=_.u;this.Rd=_.s}};

var Xz;var Zz;_.Uz=function(a){return a.Db===a.getContext().Db};_.Vz=function(){return _.r};_.AD=function(a){for(var c=(0,_.O)(),f=0;f<a.length;f++)c[a[f]]=_.r;return function(a){return!!c[a.Db]}};
var Wz=function(a,c){var f=Xz[a];return function(a){if(!c.Ma()&&((0,_.fb)(this.origin===c.Db,"Wrong origin "+this.origin+" != "+c.Db),f&&0<f.length))for(var h=[],l=this.callback,n=f.length,q=0;q<f.length;q++){var t=f[q].call(c,a,c),v=(0,_.ma)(function(a,f){h[a]=f;0===--n&&(c.Ma()||l(h))},q);if(t&&!(t instanceof _.Tz)&&"function"===typeof t.then){var w=new _.Tz;t.then(function(a){w.lc(a)});t=w}t&&t instanceof _.Tz?t.Ed(v):v(t)}}};
_.Yz=function(a,c,f){(0,_.fb)("_default"!=a,"Cannot update default api");Zz[a]={map:c,filter:f}};_.$z=function(a,c,f){(0,_.fb)("_default"!=a,"Cannot update default api");(0,_.N)(Zz,a,{map:{},filter:_.Uz}).map[c]=f};_.aA=function(a,c){(0,_.N)(Zz,"_default",{map:{},filter:_.Vz}).map[a]=c;(0,_.DC)(_.Sm.B,function(f){f.Q(a,c,_.Vz)})};_.Mq=function(){return _.Sm};
_.bA=function(a){a=a||{};this.Pt=_.u;this.xu=(0,_.O)();this.B=(0,_.O)();this.M=a._window||_.Ia;this.ha=this.M.location.href;this.Oc=(this.kg=this.M.document.referrer||(0,_.Ua)(this.ha,"parent",""))?(0,_.Ua)(this.ha,"pfname",""):"";this.wn=(this.Ka=this.kg?(0,_.Ua)(this.ha,"id",""):"")?this.Oc+"/"+this.Ka:"";this.Db=_.Rb.Pq(this.ha);if(this.Ka){var c={};c.rpcAddr=a._parentRpcAddr||"..";c.retAddr=a._parentRetAddr||this.Ka;c.origin=_.Rb.Pq((0,_.Ua)(this.ha,"parent",this.ha));c.frameName=this.Oc;this.G=
this.Pe(c)}else this.G=_.s};var cA=function(a,c,f){var g=c.canvasUrl;if(!g)return f;(0,_.fb)(!c.allowPost,"Post is not supported when using canvas url");var h=c.url;(0,_.fb)(h&&_.Rb.Pq(h)===a.Db&&_.Rb.Pq(g)===a.Db,"Wrong origin for canvas or hidden url "+g);c.url=g;c.waitForOnload=_.r;delete c.canvasUrl;var l=a.M.document;return function(a){var c=a.Aa(),g=c.location.hash,g=(0,_.ua)(l,h)+(/#/.test(h)?g.replace(/^#/,"&"):g);c.location.replace(g);f&&f(a)}};
var dA=function(a,c,f){var g=c.relayOpen;if(g){var h=a.G;g instanceof _.$?(h=g,c.relayOpen=0):0<g&&(c.relayOpen=g-1);if(h){delete c.openerIframe;(0,_.fb)(!!h.wF,"Relaying iframe open is disabled");if(g=c.style)if(g=_.eA[g])c.context=a,g(c),c.context=_.p;h.wF(c,f);return _.r}}return _.u};
var fA=function(a,c,f){var g=c.style;if(g)if((0,_.fb)(!!_.gA,"Defer style is disabled, when requesting style "+g),_.hA[g])a.zt(c);else return iA(g,function(){(0,_.fb)(!!_.hA[g],"Fail to load style - "+g);a.open(c,f)}),_.r;return _.u};_.$=function(a,c,f,g){this.Pt=_.u;this.zh=a;this.Nc=c;this.wn=f;this.zd=g;this.re=g.retAddr;this.Db=g.origin;this.yJ=g.iframeEl;this.bG=g.where;this.Ly=[];this.Ce("_default");if((0,_.Qa)(g,"apis"))for(a=g.apis||[],c=0;c<a.length;c++)this.Ce(a[c]);this.zh.B[f]=this};
_.jA=function(a,c,f,g){a.send(c,f,g,_.Vz)};_.gA=function(a){return _.hA[a]};var iA=function(a,c){_.Yi.load("gapi.iframes.style."+a,c)};var er=function(a){"number"===typeof a&&(a=String(a)+"px");return a};var lA=function(a,c){function f(a){if(a&&h){var f;c.Ga&&c.pn&&(f=function(){c.Ga(_.r)});c.um&&c.um.call(g,c.Ya);c.sender?c.sender(c.Ya,f):(0,_.jA)(h,c.message,c.Ya,f);c.Ga&&!c.pn&&c.Ga(_.r)}else c.Ga&&c.Ga(_.u)}var g=a,h=g.G,l=_.r;c.filter&&(l=c.filter.call(c.qg,c.Ya));l instanceof _.Tz?l.Ed(f):f(l)}; _.mA=function(a,c){var f={};if(c)for(var g in c)(0,_.Qa)(c,g)&&(0,_.Qa)(nA,g)&&oA.test(c[g])&&(f[g]=c[g]);return f};
var lr=/^[\w\.\-]*$/;_.k=_.bA.prototype;_.k.Ma=(0,_.y)("Pt");_.k.ua=function(){if(!this.Ma()){for(var a=0;a<this.B.length;a++)this.B[a].ua();this.Pt=_.r}};_.k.Tp=(0,_.y)("wn");_.k.Aa=(0,_.y)("M");_.k.sj=function(a,c){this.xu[a]=c};_.k.$h=function(a){return this.xu[a]};
_.k.Pe=function(a){(0,_.fb)(!this.Ma(),"Cannot attach iframe in disposed context");a.rpcAddr||(a.rpcAddr=a.id);a.retAddr||(a.retAddr="..");a.origin||(a.origin=_.Rb.Pq(a.url));a.frameName||(a.frameName=a.id?this.wn+"/"+a.id:"");var c=a.frameName;if(this.B[c])return this.B[c];var f=a.rpcAddr,g=f;(0,_.Qa)(a,"origin")&&(g=f+"|"+a.origin);var h=a.retAddr,l=a.rpctoken;l||(l=(l=a.iframeEl)&&(l.getAttribute("data-postorigin")||l.src)||a.url,l=(0,_.Ua)(l,"rpctoken"));a._rpcReadyFn=(0,_.Mz)(g,h,l,a._popupWindow);
g=((window.gadgets||{}).rpc||{}).setAuthToken;l&&g&&g(f,l);var n=new _.$(this,f,c,a),q=a.messageHandlersFilter;(0,_.DC)(a.messageHandlers,function(a,c){n.Q(c,a,q)});a.setRpcReady&&n.vj();(0,_.jA)(n,"_g_rpcReady");return n};_.k.KC=function(a){delete a.frameName;var c=a.id;!c||lr.test(c)&&!this.Aa().document.getElementById(c)||((0,_.kd)("Ignoring requested iframe ID - "+c),delete a.id)};
_.k.cj=function(a){(0,_.fb)(!this.Ma(),"Cannot open iframe in disposed context");this.zt&&this.zt(a);var c=a.frameName;if(c&&this.B[c])return this.B[c];this.KC(a);c=a.url;(0,_.fb)(c,"No url for new iframe");(a.queryParams=a.queryParams||{}).usegapi="1";a.pfname=this.wn;var f=this.te&&this.te(c,a);if(!f){var g=a.where;(0,_.fb)(!!g,"No location for new iframe");g=(0,_.tb)(c,g,a);a.iframeEl=g;f=g.getAttribute("id")}a.rpcAddr=a.id=f;a.origin=_.Rb.Pq(a.eurl);this.Bf&&this.Bf(a,g);c=this.Pe(a);c.TC&&c.TC(c,
a);if("function"===typeof a.onCreate)a.onCreate(c);a.disableRelayOpen||c.Ce("_open");return c};_.k.open=function(a,c){(0,_.fb)(!this.Ma(),"Cannot open iframe in disposed context");var f=cA(this,a,c),g=a.url;g&&!_.zd.test(g)&&(a.url=(0,_.ua)(this.M.document,g));if(!(dA(this,a,f)||fA(this,a,f)||dA(this,a,f))){var h,g=function(){f&&f(h)};a.waitForOnload&&((0,_.N)(a,"attributes",{}).onload=g);h=this.cj(a);a.waitForOnload||g()}};_.k.cq=(0,_.y)("G");_.k=_.$.prototype;_.k.Ma=(0,_.y)("Pt");
_.k.ua=function(){if(!this.Ma()){for(var a=0;a<this.Ly.length;a++)this.Jd(this.Ly[a]);delete _.Sm.B[this.Tp()];this.Pt=_.r}};_.k.getContext=(0,_.y)("zh");_.k.Tp=(0,_.y)("wn");_.k.yd=(0,_.y)("yJ");_.k.V=(0,_.y)("bG");_.k.qc=(0,_.ba)("bG");_.k.vj=function(){this.zd._rpcReadyFn()};_.k.Vm=function(a,c){this.zd[a]=c};_.k.Zf=function(a){return this.zd[a]};_.k.va=(0,_.y)("zd");_.k.Hh=function(){return this.zd.id};_.k.Pq=(0,_.y)("Db");
_.k.Q=function(a,c,f){(0,_.fb)(!this.Ma(),"Cannot register handler on disposed iframe "+a);(0,_.fb)((f||_.Uz)(this),"Rejecting untrusted message "+a);f=this.wn+":"+this.zh.wn+":"+a;1==(0,_.N)(Xz,f,[]).push(c)&&(this.Ly.push(a),(0,_.sz)(f,Wz(f,this)))};_.k.Jd=function(a,c){var f=this.wn+":"+this.zh.wn+":"+a,g=Xz[f];if(g){if(c){var h=_.Nb.call(g,c);0<=h&&g.splice(h,1)}else g.splice(0,g.length);0==g.length&&(h=_.Nb.call(this.Ly,a),0<=h&&this.Ly.splice(h,1),(0,_.wz)(f))}};_.k.fq=(0,_.y)("Ly");
_.k.Ce=function(a){this.jB=this.jB||[];if(!(0<=_.Nb.call(this.jB,a))){this.jB.push(a);a=Zz[a]||{map:{}};for(var c in a.map)(0,_.Qa)(a.map,c)&&this.Q(c,a.map[c],a.filter)}};_.k.send=function(a,c,f,g){(0,_.fb)(!this.Ma(),"Cannot send message to disposed iframe - "+a);(0,_.fb)((g||_.Uz)(this),"Wrong target for message "+a);(0,_.Az)(this.Nc,this.zh.wn+":"+this.wn+":"+a,f,c)};_.k.nK=(0,_.aa)();_.k.mK=function(a,c){(0,_.jA)(this,"_g_ping",c,a)};Xz=(0,_.O)();Zz=(0,_.O)();_.Sm=new _.bA; (0,_.aA)("_g_rpcReady",_.$.prototype.vj);(0,_.aA)("_g_discover",_.$.prototype.fq);(0,_.aA)("_g_ping",_.$.prototype.nK);
_.hA=(0,_.O)();_.eA=(0,_.O)();_.bA.prototype.zt=function(a){var c=a.style;if(c){delete a.style;var f=_.hA[c];(0,_.fb)(f,"No such style: "+c);a.context=this;f(a);a.context=_.p}};var nA={height:_.r,width:_.r},oA=/^(?!-*(?:expression|(?:moz-)?binding))(?:[.#]?-?(?:[_a-z0-9-]+)(?:-[_a-z0-9-]+)*-?|-?(?:[0-9]+(?:\.[0-9]*)?|\.[0-9]+)(?:[a-z]{1,2}|%)?|!important|)$/i;_.$.prototype.Aa=function(){if(!(0,_.Uz)(this))return _.s;var a=this.zd._popupWindow;if(a)return a;for(var c=this.Nc.split("/"),a=this.getContext().Aa(),f=0;f<c.length&&a;f++)var g=c[f],a=".."===g?a==a.parent?a.opener:a.parent:a.frames[g];return a};
_.bA.prototype.Ld=function(a,c,f){lA(this,{sender:function(a,c){var f=_.Sm.G;(0,_.DC)(_.Sm.B,function(a){a!==f&&(0,_.jA)(a,"_g_wasClosed")});(0,_.jA)(f,"_g_closeMe",a,c);(0,_.jA)(f,"_g_wasClosed")},message:"_g_closeMe",Ya:a,Ga:c,qg:f,filter:this.$h("onCloseSelfFilter")})};_.bA.prototype.po=function(a,c,f){a=a||{};lA(this,{message:"_g_restyleMe",Ya:a,Ga:c,qg:f,filter:this.$h("onRestyleSelfFilter"),pn:_.r,um:this.yh})};_.bA.prototype.yh=function(a){"auto"===a.height&&(a.height=_.Ob.Jh())};_.k=_.$.prototype;
_.k.close=function(a,c){(0,_.jA)(this,"_g_close",a,c)};_.k.sD=function(a,c){(0,_.jA)(this,"_g_restyle",a,c)};_.k.ds=function(a,c){(0,_.jA)(this,"_g_restyleDone",a,c)};_.k.qp=function(a){var c=new _.Tz;this.getContext().Ld(a,function(a){c.lc(a)},this);return c};_.k.tD=function(a){var c=new _.Tz;this.getContext().po(a,function(a){c.lc(a)},this);return c};
_.k.fs=function(a){var c=this.Zf("onRestyle");c&&c.call(this,a);a=(0,_.mA)(this,a);(c=this.yd())&&a&&"object"===typeof a&&((0,_.Qa)(a,"height")&&(a.height=er(a.height)),(0,_.Qa)(a,"width")&&(a.width=er(a.width)),(0,_.Ra)(a,c.style))};_.k.rp=function(a){var c=this.Zf("onClose");c&&c.call(this,a);this.dE&&this.dE()||(a=this.yd())&&a.parentNode&&a.parentNode.removeChild(a);if(a=this.zd.controller)c={},c.frameName=this.Tp(),(0,_.jA)(a,"_g_disposeControl",c)};
_.bA.prototype.Ij=function(a){this.sj("onCloseSelfFilter",a)};_.bA.prototype.$l=function(a){this.sj("onRestyleSelfFilter",a)};_.$.prototype.sK=function(a,c){this.Q("_g_wasRestyled",a,c)};_.$.prototype.EC=function(a,c){this.Q("_g_wasClosed",a,c)};_.$.prototype.xL=function(){this.getContext().Aa().setTimeout((0,_.H)(function(){this.ua()},this),0)};(0,_.aA)("_g_close",_.$.prototype.qp);(0,_.aA)("_g_closeMe",_.$.prototype.rp);(0,_.aA)("_g_restyle",_.$.prototype.tD);(0,_.aA)("_g_restyleMe",_.$.prototype.fs); (0,_.aA)("_g_wasClosed",_.$.prototype.xL);

var ZA=function(a,c,f){var g=a.Nc,h=c.re;f.rpcAddr=a.re+"/"+c.Nc;f.retAddr=h+"/"+g;f.frameName=c.Tp();f.origin=c.Db};var dB=function(a){a.ye||(a.ye=(0,_.O)(),a.Kh=(0,_.O)())};var eB=function(a,c,f,g){g=g||[];for(var h=0;h<g.length;h++){var l=g[h];if(l&&c&&c&&l.filter.call(a,c)){for(var n=0;n<l.hk.length;n++)c.Ce(l.hk[n]);l.Tc&&l.Tc(c,f);g[h]!==l&&h--}}};
var fB=/^https?:\/\/[^\/%\\?#\s]+$/i,bB={longdesc:_.r,name:_.r,src:_.r,frameborder:_.r,marginwidth:_.r,marginheight:_.r,scrolling:_.r,align:_.r,height:_.r,width:_.r,id:_.r,"class":_.r,title:_.r,tabindex:_.r,hspace:_.r,vspace:_.r,allowtransparency:_.r};
_.bA.prototype.Ei=function(a,c){var f=c||{},g=a.setRpcReady,h=a.iframe,l=f.iframe,n=a.rpctoken;if(l){var q={};ZA(h,l,q);q.rpctoken=n;q.role=a.role;q.data=a.data;q.setRpcReady=g;var t={};ZA(l,h,t);t.rpctoken=n;t.role=f.role;t.data=f.data;t.setRpcReady=1;(0,_.jA)(h,"_g_connect",q,function(){g||(0,_.jA)(l,"_g_connect",t)});g&&(0,_.jA)(l,"_g_connect",t)}else f={selfConnect:1},f.role=a.role,f.data=a.data,(0,_.jA)(h,"_g_connect",f)};_.k=_.$.prototype;
_.k.XH=function(a){var c;a=a||{};a.selfConnect||(0,_.fb)(fB.test(a.origin),"Illegal origin for connected iframe - "+a.origin);if(a.selfConnect)c=this;else{var f={};f.rpctoken=a.rpctoken;f.rpcAddr=a.rpcAddr;f.retAddr=a.retAddr;f.origin=a.origin;c=f.frameName=a.frameName;var g=f.setRpcReady=a.setRpcReady;c=this.zh.B[c];c?g&&(c.vj(),(0,_.jA)(c,"_g_rpcReady")):c=this.zh.Pe(f)}f=this.zh;g=a.role||"";a=a.data;dB(f);g=g||"";(0,_.N)(f.ye,g,[]).push({qg:c.Tp(),data:a});eB(f,c,a,f.Kh[g])};
_.k.TC=function(a,c){c._relayedDepth||(0,_.jA)(a,"_g_connect",{role:"_opener",selfConnect:1})};
_.k.wF=function(a,c){var f=this,g=a.messageHandlers,h=a.messageHandlersFilter,l=a.onClose;a.messageHandlers=_.s;a.messageHandlersFilter=_.s;a.onClose=_.s;(0,_.jA)(this,"_g_open",a,function(n){var q=n[0],t=q.frameName;n={};var v=f.re,w=q.retAddr;n.rpcAddr=f.Nc+"/"+q.rpcAddr;n.retAddr=w+"/"+v;n.frameName=t;n.origin=q.origin;n.apis=q.apis;n.rpctoken=a.rpctoken;n.messageHandlers=g;n.messageHandlersFilter=h;n.onClose=l;(q=f.zh.B[t])||(q=f.zh.Pe(n));c&&c(q)})};
_.k.KC=function(a){(0,_.fb)(!a.url||(0,_.Yb)(a.url),"Illegal url for new iframe - "+a.url);var c=a.attributes||{},f={},g;for(g in c)(0,_.Qa)(c,g)&&(0,_.Qa)(bB,g)&&(f[g]=c[g]);(0,_.Qa)(c,"style")&&(c=c.style,"object"===typeof c&&(f.style=(0,_.mA)(this,c)));a.attributes=f};
_.k.hK=function(a){a=a||{};this.KC(a);var c=a._relayedDepth||0;a._relayedDepth=c+1;a.openerIframe=this;var f=new _.Tz,g=a.rpctoken;delete a.rpctoken;this.zh.open(a,(0,_.H)(function(a){var l=a.zd.apis,n={};ZA(a,this,n);0==c&&(n.role="_opener");n.setRpcReady=1;n.rpctoken=g;(0,_.jA)(a,"_g_connect",n);n={};n.apis=l;n.rpcAddr=a.Nc;n.retAddr=a.re;n.frameName=a.Tp();n.origin=a.Db;f.lc(n)},this));return f};
_.bA.prototype.wc=function(a,c,f,g){dB(this);f=f||[];a=a||"";c={filter:g||_.Uz,Tc:c,hk:f};(0,_.N)(this.Kh,a,[]).push(c);a=this.ye[a]||[];for(g=0;g<a.length;g++)eB(this,this.B[a[g].qg],a[g].data,[c])};_.bA.prototype.xg=function(a,c){var f=(0,_.N)(this.Kh,a,[]);if(c)for(var g=0,h=_.u;!h&&g<f.length;g++)f[g].Tc===c&&(h=_.r,f.splice(g,1));else f.splice(0,f.length)};_.bA.prototype.qa=function(a,c,f){function g(c){h.xg("_opener",g);a&&a.call(this,c)}var h=this;this.wc("_opener",g,c,f)};
_.$.prototype.BK=function(a){this.getContext().qa(function(c){c.send("_g_wasRestyled",a)},_.s,_.Vz)};var gB=_.Sm.G;gB&&gB.Q("_g_restyleDone",_.$.prototype.BK,_.Vz);(0,_.aA)("_g_connect",_.$.prototype.XH);var hB={};hB._g_open=_.$.prototype.hK;(0,_.Yz)("_open",hB,_.Vz);

(0,_.Q)("gapi.Future",_.Tz);(0,_.Q)("gapi.Future.prototype.resolve",_.Tz.prototype.lc);(0,_.Q)("gapi.Future.prototype.setCallback",_.Tz.prototype.Ed);
(0,_.Q)("gapi.iframes.create",_.tb);
(0,_.Q)("gapi.iframes.registerStyle",function(a,c){_.hA[a]=c});(0,_.Q)("gapi.iframes.registerBeforeOpenStyle",function(a,c){_.eA[a]=c});(0,_.Q)("gapi.iframes.getStyle",_.gA);(0,_.Q)("gapi.iframes.getBeforeOpenStyle",function(a){return _.eA[a]});(0,_.Q)("gapi.iframes.registerIframesApi",_.Yz);(0,_.Q)("gapi.iframes.registerIframesApiHandler",_.$z);(0,_.Q)("gapi.iframes.getContext",_.Mq);(0,_.Q)("gapi.iframes.SAME_ORIGIN_IFRAMES_FILTER",_.Uz);(0,_.Q)("gapi.iframes.CROSS_ORIGIN_IFRAMES_FILTER",_.Vz);
(0,_.Q)("gapi.iframes.makeWhiteListIframesFilter",_.AD);(0,_.Q)("gapi.iframes.Context",_.bA);(0,_.Q)("gapi.iframes.Context.prototype.isDisposed",_.bA.prototype.Ma);(0,_.Q)("gapi.iframes.Context.prototype.getWindow",_.bA.prototype.Aa);(0,_.Q)("gapi.iframes.Context.prototype.getFrameName",_.bA.prototype.Tp);(0,_.Q)("gapi.iframes.Context.prototype.getGlobalParam",_.bA.prototype.$h);(0,_.Q)("gapi.iframes.Context.prototype.setGlobalParam",_.bA.prototype.sj);
(0,_.Q)("gapi.iframes.Context.prototype.open",_.bA.prototype.open);(0,_.Q)("gapi.iframes.Context.prototype.openChild",_.bA.prototype.cj);(0,_.Q)("gapi.iframes.Context.prototype.getParentIframe",_.bA.prototype.cq);(0,_.Q)("gapi.iframes.Context.prototype.closeSelf",_.bA.prototype.Ld);(0,_.Q)("gapi.iframes.Context.prototype.restyleSelf",_.bA.prototype.po);(0,_.Q)("gapi.iframes.Context.prototype.setCloseSelfFilter",_.bA.prototype.Ij);(0,_.Q)("gapi.iframes.Context.prototype.setRestyleSelfFilter",_.bA.prototype.$l);
(0,_.Q)("gapi.iframes.Iframe",_.$);(0,_.Q)("gapi.iframes.Iframe.prototype.isDisposed",_.$.prototype.Ma);(0,_.Q)("gapi.iframes.Iframe.prototype.getContext",_.$.prototype.getContext);(0,_.Q)("gapi.iframes.Iframe.prototype.getFrameName",_.$.prototype.Tp);(0,_.Q)("gapi.iframes.Iframe.prototype.getId",_.$.prototype.Hh);(0,_.Q)("gapi.iframes.Iframe.prototype.register",_.$.prototype.Q);(0,_.Q)("gapi.iframes.Iframe.prototype.unregister",_.$.prototype.Jd);(0,_.Q)("gapi.iframes.Iframe.prototype.send",_.$.prototype.send);
(0,_.Q)("gapi.iframes.Iframe.prototype.applyIframesApi",_.$.prototype.Ce);(0,_.Q)("gapi.iframes.Iframe.prototype.getIframeEl",_.$.prototype.yd);(0,_.Q)("gapi.iframes.Iframe.prototype.getSiteEl",_.$.prototype.V);(0,_.Q)("gapi.iframes.Iframe.prototype.setSiteEl",_.$.prototype.qc);(0,_.Q)("gapi.iframes.Iframe.prototype.getWindow",_.$.prototype.Aa);(0,_.Q)("gapi.iframes.Iframe.prototype.getOrigin",_.$.prototype.Pq);(0,_.Q)("gapi.iframes.Iframe.prototype.close",_.$.prototype.close);
(0,_.Q)("gapi.iframes.Iframe.prototype.restyle",_.$.prototype.sD);(0,_.Q)("gapi.iframes.Iframe.prototype.restyleDone",_.$.prototype.ds);(0,_.Q)("gapi.iframes.Iframe.prototype.registerWasRestyled",_.$.prototype.sK);(0,_.Q)("gapi.iframes.Iframe.prototype.registerWasClosed",_.$.prototype.EC);(0,_.Q)("gapi.iframes.Iframe.prototype.getParam",_.$.prototype.Zf);(0,_.Q)("gapi.iframes.Iframe.prototype.setParam",_.$.prototype.Vm);(0,_.Q)("gapi.iframes.Iframe.prototype.ping",_.$.prototype.mK);

(0,_.Q)("gapi.iframes.Context.prototype.addOnConnectHandler",_.bA.prototype.wc);(0,_.Q)("gapi.iframes.Context.prototype.removeOnConnectHandler",_.bA.prototype.xg);(0,_.Q)("gapi.iframes.Context.prototype.addOnOpenerHandler",_.bA.prototype.qa);(0,_.Q)("gapi.iframes.Context.prototype.connectIframes",_.bA.prototype.Ei);

_.Sb=window.iframer={};_.V={};
_.ne=2147483648*Math.random()|0;
var $t;var yn;var zt;var Ze;var Ye;var Xe;var We;var Ve;var Ie;var Je;var Ke;var Le;var Me;_.Ge=function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};_.mr=function(a,c){return-1!=a.indexOf(c)};
_.He=function(a,c){if(c)return a.replace(Ie,"&amp;").replace(Je,"&lt;").replace(Ke,"&gt;").replace(Le,"&quot;");if(!Me.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(Ie,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Je,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Ke,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Le,"&quot;"));return a};_.nr=function(a,c){return 0==a.lastIndexOf(c,0)};_.Ne=function(){return _.D.navigator?_.D.navigator.userAgent:_.s};var Oe=function(){return _.D.navigator};
var Pe=function(){var a=_.D.document;return a?a.documentMode:_.p};
_.as=function(a){var c;if(!(c=Zk[a])){c=0;for(var f=(0,_.Ge)(String(Se)).split("."),g=(0,_.Ge)(String(a)).split("."),h=Math.max(f.length,g.length),l=0;0==c&&l<h;l++){var n=f[l]||"",q=g[l]||"",t=RegExp("(\\d*)(\\D*)","g"),v=RegExp("(\\d*)(\\D*)","g");do{var w=t.exec(n)||["","",""],A=v.exec(q)||["","",""];if(0==w[0].length&&0==A[0].length)break;c=((0==w[1].length?0:(0,window.parseInt)(w[1],10))<(0==A[1].length?0:(0,window.parseInt)(A[1],10))?-1:(0==w[1].length?0:(0,window.parseInt)(w[1],10))>(0==A[1].length?
0:(0,window.parseInt)(A[1],10))?1:0)||((0==w[2].length)<(0==A[2].length)?-1:(0==w[2].length)>(0==A[2].length)?1:0)||(w[2]<A[2]?-1:w[2]>A[2]?1:0)}while(0==c)}c=Zk[a]=0<=c}return c};_.Te=function(a){return _.W&&Ue>=a};Me=/[&<>\"]/;Le=/\"/g;Ke=/>/g;Je=/</g;Ie=/&/g;Ze=Ye=Xe=We=Ve=_.u;var et;if(et=(0,_.Ne)()){var ht=Oe();Ve=(0,_.nr)(et,"Opera");We=!Ve&&((0,_.mr)(et,"MSIE")||(0,_.mr)(et,"Trident"));Ye=(Xe=!Ve&&(0,_.mr)(et,"WebKit"))&&(0,_.mr)(et,"Mobile");Ze=!Ve&&!Xe&&!We&&"Gecko"==ht.product}_.cf=Ve;
_.W=We;_.df=Ze;_.ef=Xe;_.ff=Ye;zt=Oe();yn=zt&&zt.platform||"";_.$e=(0,_.mr)(yn,"Mac");_.Eh=(0,_.mr)(yn,"Win");_.tk=(0,_.mr)(yn,"Linux");_.zn=!!Oe()&&(0,_.mr)(Oe().appVersion||"","X11");
t:{var Eu="",Fu;if(_.cf&&_.D.opera)var Ku=_.D.opera.version,Eu="function"==typeof Ku?Ku():Ku;else if(_.df?Fu=/rv\:([^\);]+)(\)|;)/:_.W?Fu=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:_.ef&&(Fu=/WebKit\/(\S+)/),Fu)var Lu=Fu.exec((0,_.Ne)()),Eu=Lu?Lu[1]:"";if(_.W){var Nu=Pe();if(Nu>(0,window.parseFloat)(Eu)){$t=String(Nu);break t}}$t=Eu}var Se=$t,Zk={},Pu=_.D.document,Ue=Pu&&_.W?Pe()||("CSS1Compat"==Pu.compatMode?(0,window.parseInt)(Se,10):5):_.p;


var pe;_.oe=function(a){return a[_.oa]||(a[_.oa]=++pe)};_.Vg=function(a){var c=typeof a;return"object"==c&&a!=_.s||"function"==c};_.Qu=function(a){return"function"==(0,_.da)(a)};_.qe=function(a){return"number"==typeof a};_.gh=function(){};_.ue=function(a,c,f){t:{for(var g=a.length,h=(0,_.fa)(a)?a.split(""):a,l=0;l<g;l++)if(l in h&&c.call(f,h[l],l,a)){c=l;break t}c=-1}return 0>c?_.s:(0,_.fa)(a)?a.charAt(c):a[c]};_.ve=function(a,c){return 0<=(0,_.we)(a,c)};
_.xe=function(a,c){var f=(0,_.we)(a,c),g;(g=0<=f)&&_.ye.splice.call(a,f,1);return g};_.ze=function(a){var c=a.length;if(0<c){for(var f=Array(c),g=0;g<c;g++)f[g]=a[g];return f}return[]};_.Ae=function(a,c,f){return 2>=arguments.length?_.ye.slice.call(a,c):_.ye.slice.call(a,c,f)};pe=0;_.ye=Array.prototype;
_.we=_.ye.indexOf?function(a,c,f){return _.ye.indexOf.call(a,c,f)}:function(a,c,f){f=f==_.s?0:0>f?Math.max(0,a.length+f):f;if((0,_.fa)(a))return(0,_.fa)(c)&&1==c.length?a.indexOf(c,f):-1;for(;f<a.length;f++)if(f in a&&a[f]===c)return f;return-1};_.Be=_.ye.forEach?function(a,c,f){_.ye.forEach.call(a,c,f)}:function(a,c,f){for(var g=a.length,h=(0,_.fa)(a)?a.split(""):a,l=0;l<g;l++)l in h&&c.call(f,h[l],l,a)};
_.Ce=_.ye.filter?function(a,c,f){return _.ye.filter.call(a,c,f)}:function(a,c,f){for(var g=a.length,h=[],l=0,n=(0,_.fa)(a)?a.split(""):a,q=0;q<g;q++)if(q in n){var t=n[q];c.call(f,t,q,a)&&(h[l++]=t)}return h};_.De=_.ye.map?function(a,c,f){return _.ye.map.call(a,c,f)}:function(a,c,f){for(var g=a.length,h=Array(g),l=(0,_.fa)(a)?a.split(""):a,n=0;n<g;n++)n in l&&(h[n]=c.call(f,l[n],n,a));return h};
_.Ee=_.ye.some?function(a,c,f){return _.ye.some.call(a,c,f)}:function(a,c,f){for(var g=a.length,h=(0,_.fa)(a)?a.split(""):a,l=0;l<g;l++)if(l in h&&c.call(f,h[l],l,a))return _.r;return _.u};_.Fe=_.ye.every?function(a,c,f){return _.ye.every.call(a,c,f)}:function(a,c,f){for(var g=a.length,h=(0,_.fa)(a)?a.split(""):a,l=0;l<g;l++)if(l in h&&!c.call(f,h[l],l,a))return _.u;return _.r};

_.V.J=_.V.J||{};_.V.J.jp=function(a){try{return!!a.document}catch(c){}return _.u};_.V.J.Uk=function(a){var c=a.parent;return a!=c&&_.V.J.jp(c)?_.V.J.Uk(c):a};_.V.J.St=function(a){var c=a.userAgent||"";a=a.product||"";return 0!=c.indexOf("Opera")&&-1==c.indexOf("WebKit")&&"Gecko"==a&&0<c.indexOf("rv:1.")};

_.dh=function(){};_.pD=function(a,c){var f=(0,_.ma)(_.eh,c);a.po||(a.po=[]);a.po.push((0,_.H)(f,_.p))};_.eh=function(a){a&&"function"==typeof a.ua&&a.ua()};_.dh.prototype.Pt=_.u;_.dh.prototype.Ma=(0,_.y)("Pt");_.dh.prototype.ua=function(){this.Pt||(this.Pt=_.r,this.C())};_.dh.prototype.C=function(){if(this.po)for(;this.po.length;)this.po.shift()()};
_.qf=function(a,c,f){for(var g in a)c.call(f,a[g],g,a)};_.hv=function(a){var c=0,f;for(f in a)c++;return c};_.hi=function(a,c){for(var f in a)if(a[f]==c)return _.r;return _.u};_.Og=function(a){for(var c in a)return _.u;return _.r};_.rf=function(a){var c={},f;for(f in a)c[f]=a[f];return c};_.sf=function(a,c){for(var f,g,h=1;h<arguments.length;h++){g=arguments[h];for(f in g)a[f]=g[f];for(var l=0;l<tf.length;l++)f=tf[l],Object.prototype.hasOwnProperty.call(g,f)&&(a[f]=g[f])}};var tf="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");

_.vf=function(a){a=a.className;return(0,_.fa)(a)&&a.match(/\S+/g)||[]};_.wf=function(a,c){for(var f=(0,_.vf)(a),g=(0,_.Ae)(arguments,1),h=f.length+g.length,l=f,n=0;n<g.length;n++)(0,_.ve)(l,g[n])||l.push(g[n]);a.className=f.join(" ");return f.length==h};_.Bf=function(a,c){var f=c||window.document;return f.querySelectorAll&&f.querySelector?f.querySelectorAll("."+a):f.getElementsByClassName?f.getElementsByClassName(a):(0,_.Cf)(window.document,"*",a,c)};
_.Df=function(a,c){var f=c||window.document,g=_.s;return(g=f.querySelectorAll&&f.querySelector?f.querySelector("."+a):(0,_.Bf)(a,c)[0])||_.s};
_.Cf=function(a,c,f,g){a=g||a;c=c&&"*"!=c?c.toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(c||f))return a.querySelectorAll(c+(f?"."+f:""));if(f&&a.getElementsByClassName){a=a.getElementsByClassName(f);if(c){g={};for(var h=0,l=0,n;n=a[l];l++)c==n.nodeName&&(g[h++]=n);g.length=h;return g}return a}a=a.getElementsByTagName(c||"*");if(f){g={};for(l=h=0;n=a[l];l++)c=n.className,"function"==typeof c.split&&(0,_.ve)(c.split(/\s+/),f)&&(g[h++]=n);g.length=h;return g}return a};
_.Ef=function(a,c){(0,_.qf)(c,function(c,g){"style"==g?a.style.cssText=c:"class"==g?a.className=c:"for"==g?a.htmlFor=c:g in Ff?a.setAttribute(Ff[g],c):(0,_.nr)(g,"aria-")||(0,_.nr)(g,"data-")?a.setAttribute(g,c):a[g]=c})};
_.Mf=function(a,c){var f=c[0],g=c[1];if(!Nf&&g&&(g.name||g.type)){f=["<",f];g.name&&f.push(' name="',(0,_.He)(g.name),'"');if(g.type){f.push(' type="',(0,_.He)(g.type),'"');var h={};(0,_.sf)(h,g);delete h.type;g=h}f.push(">");f=f.join("")}f=a.createElement(f);g&&((0,_.fa)(g)?f.className=g:(0,_.ea)(g)?_.wf.apply(_.s,[f].concat(g)):(0,_.Ef)(f,g));2<c.length&&(0,_.Of)(a,f,c,2);return f};
_.Of=function(a,c,f,g){function h(f){f&&c.appendChild((0,_.fa)(f)?a.createTextNode(f):f)}for(;g<f.length;g++){var l=f[g];!(0,_.re)(l)||(0,_.Vg)(l)&&0<l.nodeType?h(l):(0,_.Be)(Pf(l)?(0,_.ze)(l):l,h)}};_.Rf=function(a,c){c.parentNode&&c.parentNode.insertBefore(a,c)};_.Tf=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):_.s};_.Uf=function(a){var c,f=a.parentNode;if(f&&11!=f.nodeType){if(a.removeNode)return a.removeNode(_.u);for(;c=a.firstChild;)f.insertBefore(c,a);return(0,_.Tf)(a)}};
_.Vf=function(a){return a.firstElementChild!=_.p?a.firstElementChild:(0,_.Wf)(a.firstChild,_.r)};_.Wf=function(a,c){for(;a&&1!=a.nodeType;)a=c?a.nextSibling:a.previousSibling;return a};_.Yf=function(a,c){if(a.contains&&1==c.nodeType)return a==c||a.contains(c);if("undefined"!=typeof a.compareDocumentPosition)return a==c||Boolean(a.compareDocumentPosition(c)&16);for(;c&&a!=c;)c=c.parentNode;return c==a};_.cg=function(a){var c=[];(0,_.bg)(a,c,_.u);return c.join("")};
_.bg=function(a,c,f){if(!(a.nodeName in dg))if(3==a.nodeType)f?c.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):c.push(a.nodeValue);else if(a.nodeName in eg)c.push(eg[a.nodeName]);else for(a=a.firstChild;a;)(0,_.bg)(a,c,f),a=a.nextSibling};var Pf=function(a){if(a&&"number"==typeof a.length){if((0,_.Vg)(a))return"function"==typeof a.item||"string"==typeof a.item;if((0,_.Qu)(a))return"function"==typeof a.item}return _.u};_.yf=function(a){this.B=a||_.D.document||window.document};
var Nf=!_.W||(0,_.Te)(9);!_.df&&!_.W||_.W&&(0,_.Te)(9)||_.df&&(0,_.as)("1.9.1");_.ag=_.W&&!(0,_.as)("9");var Ff={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"},dg={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},eg={IMG:" ",BR:"\n"};_.k=_.yf.prototype;_.k.Z=function(a){return(0,_.fa)(a)?this.B.getElementById(a):a};_.k.ca=function(a,c,f){return(0,_.Mf)(this.B,arguments)};_.k.createElement=function(a){return this.B.createElement(a)}; _.k.Aa=function(){return this.B.parentWindow||this.B.defaultView};_.k.appendChild=function(a,c){a.appendChild(c)};_.k.Sl=_.Rf;_.k.removeNode=_.Tf;_.k.Hp=_.Uf;_.k.Yd=_.Vf;_.k.contains=_.Yf;

_.fh=function(a,c){for(var f=a.split("."),g=c||_.D,h;h=f.shift();)if(g[h]!=_.s)g=g[h];else return _.s;return g};_.hh=function(a){_.ih[_.ih.length]=a;if(_.jh)for(var c=0;c<_.kh.length;c++)a((0,_.H)(_.kh[c].B,_.kh[c]))};var lh=function(a){lh[" "](a);return a};_.mh=function(a,c){this.type=a;this.currentTarget=this.target=c};_.nh=function(a,c){a&&this.rb(a,c)};_.wB=function(a){try{return!(!a||!a[cC])}catch(c){return _.u}};
var oh=function(a,c,f,g,h,l){this.lb=a;this.xA=c;this.src=f;this.type=g;this.capture=!!h;this.Tc=l;this.key=++Lh;this.Zc=this.If=_.u};var iv=function(a){a.Zc=_.r;a.lb=_.s;a.xA=_.s;a.src=_.s;a.Tc=_.s};var jv=function(a){this.src=a;this.B={};this.G=0};var kv=function(a,c){var f=c.type;if(!(f in a.B))return _.u;var g=(0,_.xe)(a.B[f],c);g&&(iv(c),0==a.B[f].length&&(delete a.B[f],a.G--));return g};_.lv=function(a,c,f,g,h){a=a.B[c];c=-1;a&&(c=mv(a,f,g,h));return-1<c?a[c]:_.s};
var mv=function(a,c,f,g){for(var h=0;h<a.length;++h){var l=a[h];if(!l.Zc&&l.lb==c&&l.capture==!!f&&l.Tc==g)return h}return-1};_.ph=function(a,c,f,g,h){if((0,_.ea)(c)){for(var l=0;l<c.length;l++)(0,_.ph)(a,c[l],f,g,h);return _.s}f=(0,_.dC)(f);return(0,_.wB)(a)?a.R(c,f,g,h):qh(a,c,f,_.u,g,h)};
var qh=function(a,c,f,g,h,l){c||(0,_.m)(Error("u"));var n=!!h,q=(0,_.oe)(a),t=sh[q];t||(sh[q]=t=new jv(a));f=t.add(c,f,g,h,l);if(f.xA)return f;g=th();f.xA=g;g.src=a;g.lb=f;a.addEventListener?a.addEventListener(c,g,n):a.attachEvent(c in vh?vh[c]:vh[c]="on"+c,g);return rh[f.key]=f};var th=function(){var a=xh,c=yh?function(f){return a.call(c.src,c.lb,f)}:function(f){f=a.call(c.src,c.lb,f);if(!f)return f};return c};
_.zh=function(a,c,f,g,h){if((0,_.ea)(c)){for(var l=0;l<c.length;l++)(0,_.zh)(a,c[l],f,g,h);return _.s}f=(0,_.dC)(f);return(0,_.wB)(a)?a.vp.add(c,f,_.r,g,h):qh(a,c,f,_.r,g,h)};_.Ah=function(a,c,f,g,h){if((0,_.ea)(c)){for(var l=0;l<c.length;l++)(0,_.Ah)(a,c[l],f,g,h);return _.s}f=(0,_.dC)(f);if((0,_.wB)(a))return a.rg(c,f,g,h);if(!a)return _.u;g=!!g;if(a=(0,_.nv)(a))if(c=(0,_.lv)(a,c,f,g,h))return(0,_.Ch)(c);return _.u};
_.Ch=function(a){if((0,_.qe)(a)||!a||a.Zc)return _.u;var c=a.src;if((0,_.wB)(c))return kv(c.vp,a);var f=a.type,g=a.xA;c.removeEventListener?c.removeEventListener(f,g,a.capture):c.detachEvent&&c.detachEvent(f in vh?vh[f]:vh[f]="on"+f,g);(f=(0,_.nv)(c))?(kv(f,a),0==f.G&&(f.src=_.s,delete sh[(0,_.oe)(c)])):iv(a);delete rh[a.key];return _.r};var Fh=function(a,c,f,g){var h=1;if(a=(0,_.nv)(a))if(c=a.B[c])for(c=(0,_.ze)(c),a=0;a<c.length;a++){var l=c[a];l&&l.capture==f&&!l.Zc&&(h&=Gh(l,g)!==_.u)}return Boolean(h)};
var Gh=function(a,c){var f=a.lb,g=a.Tc||a.src;a.If&&(0,_.Ch)(a);return f.call(g,c)};
var xh=function(a,c){if(a.Zc)return _.r;if(!yh){var f=c||(0,_.fh)("window.event"),g=new _.nh(f,this),h=_.r;if(!(0>f.keyCode||f.returnValue!=_.p)){t:{var l=_.u;if(0==f.keyCode)try{f.keyCode=-1;break t}catch(n){l=_.r}if(l||f.returnValue==_.p)f.returnValue=_.r}f=[];for(l=g.currentTarget;l;l=l.parentNode)f.push(l);for(var l=a.type,q=f.length-1;!g.Ad&&0<=q;q--)g.currentTarget=f[q],h&=Fh(f[q],l,_.r,g);for(q=0;!g.Ad&&q<f.length;q++)g.currentTarget=f[q],h&=Fh(f[q],l,_.u,g)}return h}return Gh(a,new _.nh(c,
this))};_.nv=function(a){return a[_.oa]?sh[(0,_.oe)(a)]||_.s:_.s};_.dC=function(a){return(0,_.Qu)(a)?a:a[lC]||(a[lC]=function(c){return a.handleEvent(c)})};_.Hh=function(){this.vp=new jv(this);this.kg=this};var pC=function(a,c,f,g){c=a.vp.B[c];if(!c)return _.r;c=(0,_.ze)(c);for(var h=_.r,l=0;l<c.length;++l){var n=c[l];if(n&&!n.Zc&&n.capture==f){var q=n.lb,t=n.Tc||n.src;n.If&&kv(a.vp,n);h=q.call(t,g)!==_.u&&h}}return h&&g.Tg!=_.u};_.ih=[];_.kh=[];_.jh=_.u;
lh[" "]=_.gh;var Jh;var yh;_.Ih=!_.W||(0,_.Te)(9);yh=!_.W||(0,_.Te)(9);Jh=_.W&&!(0,_.as)("9");!_.ef||(0,_.as)("528");_.df&&(0,_.as)("1.9b")||_.W&&(0,_.as)("8")||_.cf&&(0,_.as)("9.5")||_.ef&&(0,_.as)("528");_.df&&!(0,_.as)("8")||_.W&&(0,_.as)("9");_.k=_.mh.prototype;_.k.C=(0,_.x)();_.k.ua=(0,_.x)();_.k.Ad=_.u;_.k.defaultPrevented=_.u;_.k.Tg=_.r;_.k.stopPropagation=function(){this.Ad=_.r};_.k.preventDefault=function(){this.defaultPrevented=_.r;this.Tg=_.u};_.ov=_.W?"focusin":"DOMFocusIn";_.pv=_.W?"focusout":"DOMFocusOut";_.qv=_.ef?"webkitTransitionEnd":_.cf?"otransitionend":"transitionend";(0,_.J)(_.nh,_.mh);_.k=_.nh.prototype;_.k.target=_.s;_.k.relatedTarget=_.s;_.k.offsetX=0;_.k.offsetY=0;_.k.clientX=0;_.k.clientY=0;_.k.screenX=0;_.k.screenY=0;_.k.button=0;_.k.keyCode=0;_.k.charCode=0;_.k.ctrlKey=_.u;_.k.altKey=_.u;_.k.shiftKey=_.u;_.k.metaKey=_.u;_.k.fj=_.u;_.k.Ta=_.s;
_.k.rb=function(a,c){var f=this.type=a.type;_.mh.call(this,f);this.target=a.target||a.srcElement;this.currentTarget=c;var g=a.relatedTarget;if(g){if(_.df){var h;t:{try{lh(g.nodeName);h=_.r;break t}catch(l){}h=_.u}h||(g=_.s)}}else"mouseover"==f?g=a.fromElement:"mouseout"==f&&(g=a.toElement);this.relatedTarget=g;this.offsetX=_.ef||a.offsetX!==_.p?a.offsetX:a.layerX;this.offsetY=_.ef||a.offsetY!==_.p?a.offsetY:a.layerY;this.clientX=a.clientX!==_.p?a.clientX:a.pageX;this.clientY=a.clientY!==_.p?a.clientY:
a.pageY;this.screenX=a.screenX||0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==f?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.fj=_.$e?a.metaKey:a.ctrlKey;this.state=a.state;this.Ta=a;a.defaultPrevented&&this.preventDefault();delete this.Ad};
_.k.stopPropagation=function(){_.nh.T.stopPropagation.call(this);this.Ta.stopPropagation?this.Ta.stopPropagation():this.Ta.cancelBubble=_.r};_.k.preventDefault=function(){_.nh.T.preventDefault.call(this);var a=this.Ta;if(a.preventDefault)a.preventDefault();else if(a.returnValue=_.u,Jh)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(c){}};_.k.Op=(0,_.y)("Ta");_.k.C=(0,_.x)();
var cC="closure_listenable_"+(1E6*Math.random()|0),Lh=0;jv.prototype.add=function(a,c,f,g,h){var l=this.B[a];l||(l=this.B[a]=[],this.G++);var n=mv(l,c,g,h);-1<n?(a=l[n],f||(a.If=_.u)):(a=new oh(c,_.s,this.src,a,!!g,h),a.If=f,l.push(a));return a};jv.prototype.remove=function(a,c,f,g){if(!(a in this.B))return _.u;var h=this.B[a];c=mv(h,c,f,g);return-1<c?(iv(h[c]),_.ye.splice.call(h,c,1),0==h.length&&(delete this.B[a],this.G--),_.r):_.u};jv.prototype.gA=function(a,c){var f=this.B[a],g=[];if(f)for(var h=0;h<f.length;++h){var l=f[h];l.capture==c&&g.push(l)}return g};
var rh={},sh={},vh={},lC="__closure_events_fn_"+(1E9*Math.random()>>>0);(0,_.hh)(function(a){xh=a(xh)});(0,_.J)(_.Hh,_.dh);_.Hh.prototype[cC]=_.r;_.k=_.Hh.prototype;_.k.Lg=_.s;_.k.tj=(0,_.ba)("Lg");_.k.addEventListener=function(a,c,f,g){(0,_.ph)(this,a,c,f,g)};_.k.removeEventListener=function(a,c,f,g){(0,_.Ah)(this,a,c,f,g)};
_.k.dispatchEvent=function(a){var c,f=this.Lg;if(f){c=[];for(var g=1;f;f=f.Lg)c.push(f),++g}f=this.kg;g=a.type||a;if((0,_.fa)(a))a=new _.mh(a,f);else if(a instanceof _.mh)a.target=a.target||f;else{var h=a;a=new _.mh(g,f);(0,_.sf)(a,h)}var h=_.r,l;if(c)for(var n=c.length-1;!a.Ad&&0<=n;n--)l=a.currentTarget=c[n],h=pC(l,g,_.r,a)&&h;a.Ad||(l=a.currentTarget=f,h=pC(l,g,_.r,a)&&h,a.Ad||(h=pC(l,g,_.u,a)&&h));if(c)for(n=0;!a.Ad&&n<c.length;n++)l=a.currentTarget=c[n],h=pC(l,g,_.u,a)&&h;return h};
_.k.C=function(){_.Hh.T.C.call(this);if(this.vp){var a=this.vp,c=0,f;for(f in a.B){for(var g=a.B[f],h=0;h<g.length;h++)++c,iv(g[h]);delete a.B[f];a.G--}}this.Lg=_.s};_.k.R=function(a,c,f,g){return this.vp.add(a,c,_.u,f,g)};_.k.rg=function(a,c,f,g){return this.vp.remove(a,c,f,g)};_.k.gA=function(a,c){return this.vp.gA(a,c)};

_.Lf=function(a){return"CSS1Compat"==a.compatMode};_.Kf=function(a){return!_.ef&&(0,_.Lf)(a)?a.documentElement:a.body};_.fg=function(a,c){this.width=a;this.height=c};_.X=function(a,c){this.x=(0,_.kf)(a)?a:0;this.y=(0,_.kf)(c)?c:0};_.zf=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};
_.Jf=function(a){var c=(0,_.Kf)(a);a=a.parentWindow||a.defaultView;return _.W&&(0,_.as)("10")&&a.pageYOffset!=c.scrollTop?new _.X(c.scrollLeft,c.scrollTop):new _.X(a.pageXOffset||c.scrollLeft,a.pageYOffset||c.scrollTop)};_.uv=function(a){a=a.document;a=(0,_.Lf)(a)?a.documentElement:a.body;return new _.fg(a.clientWidth,a.clientHeight)};_.Hf=function(a){return(0,_.Jf)(a.B)};_.hg=function(a){return(0,_.Lf)(a.B)};_.jg=function(a){return a?a.parentWindow||a.defaultView:window};
_.ig=function(a){return(0,_.uv)(a||window)};_.Qf=function(a){for(var c;c=a.firstChild;)a.removeChild(c)};_.xf=function(a){return a?new _.yf((0,_.zf)(a)):Af||(Af=new _.yf)};_.$f=function(a){if(_.ag&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var c=[];(0,_.bg)(a,c,_.r);a=c.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");_.ag||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a};
_.Zf=function(a,c){if("textContent"in a)a.textContent=c;else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=c}else(0,_.Qf)(a),a.appendChild((0,_.zf)(a).createTextNode(String(c)))};_.Sf=function(a,c){c.parentNode&&c.parentNode.insertBefore(a,c.nextSibling)};_.kg=function(a){return(0,_.fa)(a)?window.document.getElementById(a):a};
var Dg=function(a,c){var f=(0,_.fa)(c)?String(c).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"):"\\s",f=f?"|["+f+"]+":"";return a.replace(RegExp("(^"+f+")([a-z])","g"),function(a,c,f){return c+f.toUpperCase()})};_.Cg=function(a){return String(a).replace(/\-([a-z])/g,function(a,f){return f.toUpperCase()})};_.Gv=function(a,c){for(var f in c)a[f]=c[f]};_.Mg=function(a,c,f){(0,_.fa)(c)?Hg(a,f,c):(0,_.qf)(c,(0,_.ma)(Hg,a))};
var Hg=function(a,c,f){(f=(0,_.Fg)(a,f))&&(a.style[f]=c)};_.Fg=function(a,c){var f=(0,_.Cg)(c);if(a.style[f]===_.p){var g=(_.ef?"Webkit":_.df?"Moz":_.W?"ms":_.cf?"O":_.s)+Dg(c);if(a.style[g]!==_.p)return g}return f};_.lg=function(a,c){var f=(0,_.zf)(a);return f.defaultView&&f.defaultView.getComputedStyle&&(f=f.defaultView.getComputedStyle(a,_.s))?f[c]||f.getPropertyValue(c)||"":""};_.mg=function(a,c){return a.currentStyle?a.currentStyle[c]:_.s};
_.ng=function(a,c){return(0,_.lg)(a,c)||(0,_.mg)(a,c)||a.style&&a.style[c]};_.og=function(a){return(0,_.ng)(a,"position")};_.pg=function(a){a=a?(0,_.zf)(a):window.document;return!_.W||(0,_.Te)(9)||(0,_.hg)((0,_.xf)(a))?a.documentElement:a.body};
var qg=function(a){var c;try{c=a.getBoundingClientRect()}catch(f){return{left:0,top:0,right:0,bottom:0}}_.W&&a.ownerDocument.body&&(a=a.ownerDocument,c.left-=a.documentElement.clientLeft+a.body.clientLeft,c.top-=a.documentElement.clientTop+a.body.clientTop);return c};
_.rg=function(a){if(_.W&&!(0,_.Te)(8))return a.offsetParent;var c=(0,_.zf)(a),f=(0,_.ng)(a,"position"),g="fixed"==f||"absolute"==f;for(a=a.parentNode;a&&a!=c;a=a.parentNode)if(f=(0,_.ng)(a,"position"),g=g&&"static"==f&&a!=c.documentElement&&a!=c.body,!g&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||"fixed"==f||"absolute"==f||"relative"==f))return a;return _.s};
_.sg=function(a){var c,f=(0,_.zf)(a),g=(0,_.ng)(a,"position"),h=_.df&&f.getBoxObjectFor&&!a.getBoundingClientRect&&"absolute"==g&&(c=f.getBoxObjectFor(a))&&(0>c.screenX||0>c.screenY),l=new _.X(0,0),n=(0,_.pg)(f);if(a==n)return l;if(a.getBoundingClientRect)c=qg(a),a=(0,_.Hf)((0,_.xf)(f)),l.x=c.left+a.x,l.y=c.top+a.y;else if(f.getBoxObjectFor&&!h)c=f.getBoxObjectFor(a),a=f.getBoxObjectFor(n),l.x=c.screenX-a.screenX,l.y=c.screenY-a.screenY;else{c=a;do{l.x+=c.offsetLeft;l.y+=c.offsetTop;c!=a&&(l.x+=c.clientLeft||
0,l.y+=c.clientTop||0);if(_.ef&&"fixed"==(0,_.og)(c)){l.x+=f.body.scrollLeft;l.y+=f.body.scrollTop;break}c=c.offsetParent}while(c&&c!=a);if(_.cf||_.ef&&"absolute"==g)l.y-=f.body.offsetTop;for(c=a;(c=(0,_.rg)(c))&&c!=f.body&&c!=n;)l.x-=c.scrollLeft,_.cf&&"TR"==c.tagName||(l.y-=c.scrollTop)}return l};_.tg=function(a,c){var f=new _.X(0,0),g=(0,_.jg)((0,_.zf)(a)),h=a;do{var l=g==c?(0,_.sg)(h):(0,_.Hv)(h);f.x+=l.x;f.y+=l.y}while(g&&g!=c&&(h=g.frameElement)&&(g=g.parent));return f};
_.Hv=function(a){var c;if(a.getBoundingClientRect)c=qg(a),c=new _.X(c.left,c.top);else{c=(0,_.Hf)((0,_.xf)(a));var f=(0,_.sg)(a);c=new _.X(f.x-c.x,f.y-c.y)}if(_.df&&!(0,_.as)(12)){var g;_.W?g="-ms-transform":_.ef?g="-webkit-transform":_.cf?g="-o-transform":_.df&&(g="-moz-transform");var h;g&&(h=(0,_.ng)(a,g));h||(h=(0,_.ng)(a,"transform"));a=h?(a=h.match(vg))?new _.X((0,window.parseFloat)(a[1]),(0,window.parseFloat)(a[2])):new _.X(0,0):new _.X(0,0);a=new _.X(c.x+a.x,c.y+a.y)}else a=c;return a};
_.wg=function(a,c,f){c instanceof _.fg?(f=c.height,c=c.width):f==_.p&&(0,_.m)(Error("r"));a.style.width=(0,_.xg)(c,_.r);a.style.height=(0,_.xg)(f,_.r)};_.xg=function(a,c){"number"==typeof a&&(a=(c?Math.round(a):a)+"px");return a};_.yg=function(a){var c;var f=zg;if("none"!=(0,_.ng)(a,"display"))c=f(a);else{c=a.style;var g=c.display,h=c.visibility,l=c.position;c.visibility="hidden";c.position="absolute";c.display="inline";a=f(a);c.display=g;c.position=l;c.visibility=h;c=a}return c};
var zg=function(a){var c=a.offsetWidth,f=a.offsetHeight,g=_.ef&&!c&&!f;return(0,_.kf)(c)&&!g||!a.getBoundingClientRect?new _.fg(c,f):(a=qg(a),new _.fg(a.right-a.left,a.bottom-a.top))};_.fg.prototype.U=function(){return new _.fg(this.width,this.height)};_.fg.prototype.eb=function(){return!(this.width*this.height)};_.fg.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
_.fg.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};_.X.prototype.U=function(){return new _.X(this.x,this.y)};_.X.prototype.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};_.X.prototype.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};_.X.prototype.translate=function(a,c){a instanceof _.X?(this.x+=a.x,this.y+=a.y):(this.x+=a,(0,_.qe)(c)&&(this.y+=c));return this};var Af;
var vg;_.Bg=_.df?"MozUserSelect":_.ef?"WebkitUserSelect":_.s;vg=/matrix\([0-9\.\-]+, [0-9\.\-]+, [0-9\.\-]+, [0-9\.\-]+, ([0-9\.\-]+)p?x?, ([0-9\.\-]+)p?x?\)/;
_.Pg=function(a,c,f,g){this.top=a;this.right=c;this.bottom=f;this.left=g};_.Qg=function(a,c,f,g){if(/^\d+px?$/.test(c))return(0,window.parseInt)(c,10);var h=a.style[f],l=a.runtimeStyle[f];a.runtimeStyle[f]=a.currentStyle[f];a.style[f]=c;c=a.style[g];a.style[f]=h;a.runtimeStyle[f]=l;return c};var Rg=function(a,c){if("none"==(0,_.mg)(a,c+"Style"))return 0;var f=(0,_.mg)(a,c+"Width");return f in Sg?Sg[f]:(0,_.Qg)(a,f,"left","pixelLeft")};
_.Ug=function(a){if(_.W){var c=Rg(a,"borderLeft"),f=Rg(a,"borderRight"),g=Rg(a,"borderTop");a=Rg(a,"borderBottom");return new _.Pg(g,f,a,c)}c=(0,_.lg)(a,"borderLeftWidth");f=(0,_.lg)(a,"borderRightWidth");g=(0,_.lg)(a,"borderTopWidth");a=(0,_.lg)(a,"borderBottomWidth");return new _.Pg((0,window.parseFloat)(g),(0,window.parseFloat)(f),(0,window.parseFloat)(a),(0,window.parseFloat)(c))};_.Eg=function(a){return"rtl"==(0,_.ng)(a,"direction")};
_.Ig=function(a,c,f,g){this.left=a;this.top=c;this.width=f;this.height=g};_.Xg=function(a,c){var f=(0,_.xf)(c),g=_.s,g=f.B;if(_.W&&g.createStyleSheet)f=g=g.createStyleSheet(),_.W?f.cssText=a:f.innerHTML=a;else{var h=(0,_.Cf)(f.B,"head",_.p,_.p)[0];h||(g=(0,_.Cf)(f.B,"body",_.p,_.p)[0],h=f.ca("head"),g.parentNode.insertBefore(h,g));var l=g=f.ca("style");_.W?l.cssText=a:l.innerHTML=a;f.appendChild(h,g)}return g};_.Rj=function(a,c){a.style.display=c?"":"none"};
_.Ag=function(a,c){var f=a.style;"opacity"in f?f.opacity=c:"MozOpacity"in f?f.MozOpacity=c:"filter"in f&&(f.filter=""===c?"":"alpha(opacity="+100*c+")")};_.Zg=function(a,c,f){var g,h=_.df&&(_.$e||_.zn)&&(0,_.as)("1.9");c instanceof _.X?(g=c.x,c=c.y):(g=c,c=f);a.style.left=(0,_.xg)(g,h);a.style.top=(0,_.xg)(c,h)};_.ah=function(a,c,f){var g={},h;for(h in a)c.call(f,a[h],h,a)&&(g[h]=a[h]);return g};_.k=_.Pg.prototype;_.k.U=function(){return new _.Pg(this.top,this.right,this.bottom,this.left)};
_.k.contains=function(a){return this&&a?a instanceof _.Pg?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom:_.u};_.k.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};
_.k.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};_.k.translate=function(a,c){a instanceof _.X?(this.left+=a.x,this.right+=a.x,this.top+=a.y,this.bottom+=a.y):(this.left+=a,this.right+=a,(0,_.qe)(c)&&(this.top+=c,this.bottom+=c));return this};var Sg={thin:2,medium:4,thick:6};_.k=_.Ig.prototype;_.k.U=function(){return new _.Ig(this.left,this.top,this.width,this.height)};
_.k.contains=function(a){return a instanceof _.Ig?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};_.k.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
_.k.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};_.k.translate=function(a,c){a instanceof _.X?(this.left+=a.x,this.top+=a.y):(this.left+=a,(0,_.qe)(c)&&(this.top+=c));return this};

_.Mh=function(a){return new _.Pg(a.top,a.left+a.width,a.top+a.height,a.left)};var Tg=function(a,c){var f=(0,_.mg)(a,c);return f?(0,_.Qg)(a,f,"left","pixelLeft"):0};
_.kC=function(a){var c;if(_.W){c=Tg(a,"paddingLeft");var f=Tg(a,"paddingRight"),g=Tg(a,"paddingTop");a=Tg(a,"paddingBottom");c=new _.Pg(g,f,a,c)}else c=(0,_.lg)(a,"paddingLeft"),f=(0,_.lg)(a,"paddingRight"),g=(0,_.lg)(a,"paddingTop"),a=(0,_.lg)(a,"paddingBottom"),c=new _.Pg((0,window.parseFloat)(g),(0,window.parseFloat)(f),(0,window.parseFloat)(a),(0,window.parseFloat)(c));return c};
_.ug=function(a){if(1==a.nodeType)return(0,_.Hv)(a);var c=(0,_.Qu)(a.Op),f=a;a.targetTouches?f=a.targetTouches[0]:c&&a.Ta.targetTouches&&(f=a.Ta.targetTouches[0]);return new _.X(f.clientX,f.clientY)};var Wg=function(a,c){return new _.X(a.x-c.x,a.y-c.y)};_.Lg=function(a){var c=(0,_.sg)(a);a=(0,_.yg)(a);return new _.Ig(c.x,c.y,a.width,a.height)};
_.Yg=function(a){for(var c=new _.Pg(0,window.Infinity,window.Infinity,0),f=(0,_.xf)(a),g=f.B.body,h=f.B.documentElement,l=(0,_.Kf)(f.B);a=(0,_.rg)(a);)if(!(_.W&&0==a.clientWidth||_.ef&&0==a.clientHeight&&a==g||a==g||a==h||"visible"==(0,_.ng)(a,"overflow"))){var n=(0,_.sg)(a),q;q=a;if(_.df&&!(0,_.as)("1.9")){var t=(0,window.parseFloat)((0,_.lg)(q,"borderLeftWidth"));if((0,_.Eg)(q))var v=q.offsetWidth-q.clientWidth-t-(0,window.parseFloat)((0,_.lg)(q,"borderRightWidth")),t=t+v;q=new _.X(t,(0,window.parseFloat)((0,_.lg)(q,
"borderTopWidth")))}else q=new _.X(q.clientLeft,q.clientTop);n.x+=q.x;n.y+=q.y;c.top=Math.max(c.top,n.y);c.right=Math.min(c.right,n.x+a.clientWidth);c.bottom=Math.min(c.bottom,n.y+a.clientHeight);c.left=Math.max(c.left,n.x)}g=l.scrollLeft;l=l.scrollTop;c.left=Math.max(c.left,g);c.top=Math.max(c.top,l);f=(0,_.ig)(f.Aa());c.right=Math.min(c.right,g+f.width);c.bottom=Math.min(c.bottom,l+f.height);return 0<=c.top&&0<=c.left&&c.bottom>c.top&&c.right>c.left?c:_.s};
_.Nh=function(a,c,f,g){f||(a=a.parentNode);f=g==_.s;for(var h=0;a&&(f||h<=g);){if(c(a))return a;a=a.parentNode;h++}return _.s};_.$g=function(a,c){return(0,_.ve)((0,_.vf)(a),c)};
_.bh=function(a,c,f,g,h,l,n,q,t){var v=(0,_.Kv)(f),w=(0,_.Lg)(a),A=(0,_.Yg)(a);if(A){var F=new _.Ig(A.left,A.top,A.right-A.left,A.bottom-A.top),A=Math.max(w.left,F.left),z=Math.min(w.left+w.width,F.left+F.width);if(A<=z){var I=Math.max(w.top,F.top),F=Math.min(w.top+w.height,F.top+F.height);I<=F&&(w.left=A,w.top=I,w.width=z-A,w.height=F-I)}}A=(0,_.xf)(a);I=(0,_.xf)(f);A.B!=I.B&&(z=A.B.body,I=(0,_.tg)(z,I.Aa()),I=Wg(I,(0,_.sg)(z)),_.W&&!(0,_.hg)(A)&&(I=Wg(I,(0,_.Hf)(A))),w.left+=I.x,w.top+=I.y);a=(c&
4&&(0,_.Eg)(a)?c^2:c)&-5;w=new _.X(a&2?w.left+w.width:w.left,a&1?w.top+w.height:w.top);w=Wg(w,v);h&&(w.x+=(a&2?-1:1)*h.x,w.y+=(a&1?-1:1)*h.y);var E;if(n)if(t)E=t;else if(E=(0,_.Yg)(f))E.top-=v.y,E.right-=v.x,E.bottom-=v.y,E.left-=v.x;return(0,_.ch)(w,f,g,l,E,n,q)};
_.Kv=function(a){var c;if(a=a.offsetParent){var f="HTML"==a.tagName||"BODY"==a.tagName;f&&"static"==(0,_.og)(a)||(c=(0,_.sg)(a),f||(f=(f=(0,_.Eg)(a))&&_.df?-a.scrollLeft:!f||_.W&&(0,_.as)("8")||"visible"==(0,_.ng)(a,"overflowX")?a.scrollLeft:a.scrollWidth-a.clientWidth-a.scrollLeft,c=Wg(c,new _.X(f,a.scrollTop))))}return c||new _.X};
_.ch=function(a,c,f,g,h,l,n){a=a.U();var q=0,t=(f&4&&(0,_.Eg)(c)?f^2:f)&-5;f=(0,_.yg)(c);n=n?n.U():f.U();if(g||0!=t)t&2?a.x-=n.width+(g?g.right:0):g&&(a.x+=g.left),t&1?a.y-=n.height+(g?g.bottom:0):g&&(a.y+=g.top);if(l&&(h?(q=a,g=0,65==(l&65)&&(q.x<h.left||q.x>=h.right)&&(l&=-2),132==(l&132)&&(q.y<h.top||q.y>=h.bottom)&&(l&=-5),q.x<h.left&&l&1&&(q.x=h.left,g|=1),q.x<h.left&&q.x+n.width>h.right&&l&16&&(n.width=Math.max(n.width-(q.x+n.width-h.right),0),g|=4),q.x+n.width>h.right&&l&1&&(q.x=Math.max(h.right-
n.width,h.left),g|=1),l&2&&(g=g|(q.x<h.left?16:0)|(q.x+n.width>h.right?32:0)),q.y<h.top&&l&4&&(q.y=h.top,g|=2),q.y<=h.top&&q.y+n.height<h.bottom&&l&32&&(n.height=Math.max(n.height-(h.top-q.y),0),q.y=h.top,g|=8),q.y>=h.top&&q.y+n.height>h.bottom&&l&32&&(n.height=Math.max(n.height-(q.y+n.height-h.bottom),0),g|=8),q.y+n.height>h.bottom&&l&4&&(q.y=Math.max(h.bottom-n.height,h.top),g|=2),l&8&&(g=g|(q.y<h.top?64:0)|(q.y+n.height>h.bottom?128:0)),q=g):q=256,q&496))return q;(0,_.Zg)(c,a);f==n||f&&n&&f.width==
n.width&&f.height==n.height||(h=(0,_.hg)((0,_.xf)((0,_.zf)(c))),!_.W||h&&(0,_.as)("8")?(c=c.style,_.df?c.MozBoxSizing="border-box":_.ef?c.WebkitBoxSizing="border-box":c.boxSizing="border-box",c.width=Math.max(n.width,0)+"px",c.height=Math.max(n.height,0)+"px"):(a=c.style,h?(h=(0,_.kC)(c),c=(0,_.Ug)(c),a.pixelWidth=n.width-c.left-h.left-h.right-c.right,a.pixelHeight=n.height-c.top-h.top-h.bottom-c.bottom):(a.pixelWidth=n.width,a.pixelHeight=n.height)));return q};


_.Nv=function(){var a=window.document,c=0;if(a){var c=(0,_.uv)(window).height,f=a.body,g=a.documentElement;if((0,_.Lf)(a)&&g.scrollHeight)c=g.scrollHeight!=c?g.scrollHeight:g.offsetHeight;else{var a=g.scrollHeight,h=g.offsetHeight;g.clientHeight!=h&&(a=f.scrollHeight,h=f.offsetHeight);c=a>c?a>h?a:h:a<h?a:h}}return c};_.Oh=function(a){this.wb=a;this.B=a.va()};
var Ph=function(a){var c=a.wb.ci();if(a.B.anchorBox&&c&&c.yd())c=(0,_.sg)(c.yd()),a.B.anchorBox.left+=c.x,a.B.anchorBox.top+=c.y;else{c=a.B.anchor;if("_default"!=c&&"_iframe"!=c){var f=(0,_.kg)(c);if(f)a.B.anchorBox=(0,_.Lg)(f);else{(0,_.sa)("Anchor not found in DOM: "+c+'. Falling back to "_default".');a.B.anchor="_default";return}}"_iframe"==c&&(c=(0,_.ig)(),a.B.anchorBox=new _.Ig(0,0,c.width,c.height))}a.B.anchor=""};_.Qh=function(a){_.Oh.call(this,a)};
_.Ov=function(a){if(a.ye)return a.ye;var c=a.B;!c.anchorBox&&c.anchor&&Ph(a);var f=a.wb.ci();if("_default"==c.anchor&&f){var g=(0,_.Lg)((0,_.kg)(f.V()));c.anchorBox=g}if(!c.anchorBox)return(0,_.sa)("No anchor box defined."),_.s;c=new _.X(c.anchorBox.left,c.anchorBox.top);f&&(f=(0,_.tg)(f.yd(),window),a.zt=new _.X,a.zt.x=f.x,a.zt.y=f.y,c.x+=f.x,c.y+=f.y,(0,_.Sh)(window,c));a.te=c;f=(0,_.Pv)(a,_.r);a.ye=window.document.createElement("ins");a.ye.style.cssText=f;window.document.body.appendChild(a.ye);
return a.ye};_.Pv=function(a,c){var f=a.B;return"position: absolute !important;background-color: transparent !important;left: "+a.te.x+"px !important;top: "+a.te.y+"px !important;width: "+f.anchorBox.width+"px !important;height: "+f.anchorBox.height+"px !important;z-index: -10000 !important;display: "+(c?"block":"none")+" !important;"};
_.Th=function(a,c){var f=0,g=0;if(c.pageX||c.pageY)f=c.pageX,g=c.pageY;else if(c.clientX||c.clientY){var g=c.target?c.target:c.srcElement,f=g.ownerDocument&&g.ownerDocument.parentWindow?g.ownerDocument.parentWindow:window,h=0,g=0;_.W?(h=f.document.documentElement.scrollLeft,g=f.document.documentElement.scrollTop):(h=f.pageXOffset,g=f.pageYOffset);f=c.clientX+h;g=c.clientY+g}g=new _.X(f,g);return(f=(0,_.Mh)((0,_.Lg)(a)))&&f.contains(g)};
_.Sh=function(a,c){var f=window.document.body,g=(0,_.sg)(f),f=f.currentStyle||a.getComputedStyle(f,"");f.position&&"static"!=f.position&&(c.x-=g.x,c.y-=g.y)};_.Uh=function(a){var c=a.wb.ci()&&a.wb.ci().V(),c=c&&c.style.zIndex?(0,window.parseInt)(c.style.zIndex,10)+1:0;return Math.min(2147483647,Math.max(2E9,a.B.zIndex||c))};
_.Vh=function(a,c,f,g,h){h=h||{x:0,y:0};if(Wh[c]){var l=(0,_.yg)(a).width/2;h.x="top-right"==g||"bottom-right"==g?h.x+l:h.x-l}Wh[g]&&(l=(0,_.yg)(f).width/2,h.x+=l);Xh[c]&&(l=(0,_.yg)(a).height/2,h.y="right-bottom"==g||"left-bottom"==g?h.y+l:h.y-l);Xh[g]&&(h.y+=(0,_.yg)(f).height/2);(0,_.bh)(f,Yh[g],a,Yh[c],new _.X(h.x,h.y));g=(0,_.Nh)(a,function(a){return a==window.document?_.u:(a=(0,_.og)(a))&&"static"!=a});f=c=0;g&&(f=(0,_.sg)(g),c=-f.x,f=-f.y);a=a.style;(0,window.parseInt)(a.left,10)<c&&(a.left=
c+"px");(0,window.parseInt)(a.top,10)<f&&(a.top=f+"px")};_.Zh=function(a){_.Oh.call(this,a.wb);this.qa=a;this.G=_.s};var $h=function(){_.Hh.call(this);this.B=[]};if("undefined"===typeof ai)var ai={};_.Oh.prototype.Bf=function(){Ph(this)};_.Oh.prototype.onBeforeParentOpen=_.Oh.prototype.Bf;
(0,_.J)(_.Qh,_.Oh);_.Qh.prototype.open=function(){var a=this.B,c=window.document.createElement("ins");window.document.getElementById(a.container).appendChild(c);c.style.display="block";(0,_.Mg)(c,a.containerCss);this.wb.qc(c);this.wb.Pa(c)};_.Qh.prototype.Ph=function(){window.document.getElementById(this.wb.id).style.height=this.wb.height+"px"};_.Qh.prototype.close=function(){(0,_.Tf)(this.wb.V());(0,_.Tf)(this.ye);this.ye=_.s};
var Yh={"bottom-center":1,"bottom-end":7,"bottom-left":1,"bottom-right":3,"bottom-start":5,"left-bottom":1,"left-center":0,"left-top":0,"right-bottom":3,"right-center":2,"right-top":2,"top-center":0,"top-end":6,"top-left":0,"top-right":2,"top-start":4},Wh={"bottom-center":_.r,"top-center":_.r},Xh={"left-center":_.r,"right-center":_.r};
(0,_.J)(_.Zh,_.Qh);_.Zh.prototype.Bf=function(){this.qa.Bf()};_.Zh.prototype.onBeforeParentOpen=_.Zh.prototype.Bf;_.Zh.prototype.open=function(){this.qa.open();if(this.B.closeClickDetection||this.B.hideClickDetection)this.G=(0,_.ph)(window.document,["click","touchstart"],(0,_.H)(this.ha,this),_.u)};_.Zh.prototype.open=_.Zh.prototype.open;_.Zh.prototype.Ph=function(a){this.qa.Ph(a)};_.Zh.prototype.onready=_.Zh.prototype.Ph;_.Zh.prototype.M=function(a){this.qa.onRenderStart&&this.qa.onRenderStart(a)};
_.Zh.prototype.onRenderStart=_.Zh.prototype.M;_.Zh.prototype.close=function(){if(this.B.closeClickDetection||this.B.hideClickDetection)(0,_.Ch)(this.G),this.G=_.s;this.qa.close()};_.Zh.prototype.close=_.Zh.prototype.close;_.Zh.prototype.ha=function(a){(0,_.Th)(this.wb.V(),a)||(this.B.hideClickDetection&&this.qa.show?this.qa.show(_.u):this.qa.close())};
(0,_.J)($h,_.Hh);$h.prototype.C=function(){for(var a in this.B)(0,_.Ch)(a);this.B=[];this.M=_.D.clearTimeout(this.M);$h.T.C.call(this);this.dispatchEvent({type:"dispose"})};(0,_.C)("iframes.styles.createAnchor",function(){return new $h(["email","oid","o","cid"])},_.p);

var HC;_.FC=function(a){return{va:function(){return a},ci:function(){return a.openerIframe}}};var GC=function(a){(new _.Oh((0,_.FC)(a))).Bf()};for(HC="bubble circlepicker float hover hover-menu slide-menu".split(" "),_.Ju=0;_.Ju<HC.length;_.Ju++)_.eA[HC[_.Ju]]=GC;

_.bA.prototype.Tb=function(a,c,f,g){var h=c||{},l=this.G;this.qa(function(a){(0,_.DC)(h,function(c,f){a.Q(f,c,g)},this);a!==l&&a.send("_ready",n,_.p,g)},_.p,g);var n=a||{};n.height=n.height||"auto";this.yh(n);l&&l.send("_ready",n,f,_.Vz)};(0,_.Q)("gapi.iframes.Context.prototype.ready",_.bA.prototype.Tb);

});

// Copyright 2002-2013 Google Inc.
